#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AGV_Sideways

#include "Basic.hpp"

#include "AGV_Sideways_classes.hpp"
#include "AGV_Sideways_parameters.hpp"


namespace SDK
{

// Function AGV_Sideways.AGV_Sideways_C.BndEvt__AudioShapeSphere_K2Node_ComponentBoundEvent_2_OnAudioShapeInsideStateChanged__DelegateSignature
// (BlueprintEvent)
// Parameters:
// bool                                    bIsInside                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAGV_Sideways_C::BndEvt__AudioShapeSphere_K2Node_ComponentBoundEvent_2_OnAudioShapeInsideStateChanged__DelegateSignature(bool bIsInside)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AGV_Sideways_C", "BndEvt__AudioShapeSphere_K2Node_ComponentBoundEvent_2_OnAudioShapeInsideStateChanged__DelegateSignature");

	Params::AGV_Sideways_C_BndEvt__AudioShapeSphere_K2Node_ComponentBoundEvent_2_OnAudioShapeInsideStateChanged__DelegateSignature Parms{};

	Parms.bIsInside = bIsInside;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AGV_Sideways.AGV_Sideways_C.ExecuteUbergraph_AGV_Sideways
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAGV_Sideways_C::ExecuteUbergraph_AGV_Sideways(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AGV_Sideways_C", "ExecuteUbergraph_AGV_Sideways");

	Params::AGV_Sideways_C_ExecuteUbergraph_AGV_Sideways Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AGV_Sideways.AGV_Sideways_C.IsOptimized
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// bool*                                   Result                                                 (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAGV_Sideways_C::IsOptimized(bool* Result)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AGV_Sideways_C", "IsOptimized");

	Params::AGV_Sideways_C_IsOptimized Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Result != nullptr)
		*Result = Parms.Result;
}


// Function AGV_Sideways.AGV_Sideways_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void AAGV_Sideways_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AGV_Sideways_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AGV_Sideways.AGV_Sideways_C.SetRadius
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   InRadius                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void AAGV_Sideways_C::SetRadius(float InRadius)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AGV_Sideways_C", "SetRadius");

	Params::AGV_Sideways_C_SetRadius Parms{};

	Parms.InRadius = InRadius;

	UObject::ProcessEvent(Func, &Parms);
}

}

