#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AISpawnerData_Vendetta_Master_Loadout_1

#include "Basic.hpp"

#include "AISpawnerData_Vendetta_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AISpawnerData_Vendetta_Master_Loadout_1.AISpawnerData_Vendetta_Master_Loadout_1_C
// 0x0000 (0x00C8 - 0x00C8)
class UAISpawnerData_Vendetta_Master_Loadout_1_C final : public UAISpawnerData_Vendetta_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AISpawnerData_Vendetta_Master_Loadout_1_C">();
	}
	static class UAISpawnerData_Vendetta_Master_Loadout_1_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAISpawnerData_Vendetta_Master_Loadout_1_C>();
	}
};
static_assert(alignof(UAISpawnerData_Vendetta_Master_Loadout_1_C) == 0x000008, "Wrong alignment on UAISpawnerData_Vendetta_Master_Loadout_1_C");
static_assert(sizeof(UAISpawnerData_Vendetta_Master_Loadout_1_C) == 0x0000C8, "Wrong size on UAISpawnerData_Vendetta_Master_Loadout_1_C");

}

