#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Artemis_Seven_Village_TikiTorch_FX

#include "Basic.hpp"

#include "Transylvania_FireLight_Master_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Artemis_Seven_Village_TikiTorch_FX.Artemis_Seven_Village_TikiTorch_FX_C
// 0x0000 (0x0EB8 - 0x0EB8)
class AArtemis_Seven_Village_TikiTorch_FX_C final : public ATransylvania_FireLight_Master_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Artemis_Seven_Village_TikiTorch_FX_C">();
	}
	static class AArtemis_Seven_Village_TikiTorch_FX_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AArtemis_Seven_Village_TikiTorch_FX_C>();
	}
};

}

