#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AshtonIndigoLayerAnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "AnimGraphRuntime_structs.hpp"
#include "AshtonIndigoLayerAnimBP_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass AshtonIndigoLayerAnimBP.AshtonIndigoLayerAnimBP_C
// 0x1BB0 (0x1F90 - 0x03E0)
class UAshtonIndigoLayerAnimBP_C final : public UFortItemLayerAnimInstance
{
public:
	uint8                                         Pad_3D8[0x8];                                      // 0x03D8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct AshtonIndigoLayerAnimBP::FAnimBlueprintGeneratedMutableData __AnimBlueprintMutables;      // 0x03E8(0x001C)(HasGetValueTypeHash)
	uint8                                         Pad_404[0x4];                                      // 0x0404(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_PropertyAccess;             // 0x0408(0x0008)()
	struct FAnimSubsystemInstance                 AnimBlueprintExtension_Base;                       // 0x0410(0x0008)()
	struct FAnimNode_Root                         AnimGraphNode_Root_34;                             // 0x0418(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_19;                  // 0x0438(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_33;                             // 0x0500(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_18;                  // 0x0520(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_32;                             // 0x05E8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_17;                  // 0x0608(0x00C8)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_16;                  // 0x06D0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_31;                             // 0x0798(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_15;                  // 0x07B8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_30;                             // 0x0880(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_29;                             // 0x08A0(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_28;                             // 0x08C0(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_27;                             // 0x08E0(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_26;                             // 0x0900(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_25;                             // 0x0920(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_14;                  // 0x0940(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_24;                             // 0x0A08(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_13;                  // 0x0A28(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_23;                             // 0x0AF0(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_12;                  // 0x0B10(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_22;                             // 0x0BD8(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_13;                   // 0x0BF8(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_21;                             // 0x0C38(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_20;                             // 0x0C58(0x0020)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_5;                   // 0x0C78(0x0088)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_12;                   // 0x0D00(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_11;                   // 0x0D40(0x0040)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_11;                  // 0x0D80(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_19;                             // 0x0E48(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_10;                   // 0x0E68(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_9;                    // 0x0EA8(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_8;                    // 0x0EE8(0x0040)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_4;                   // 0x0F28(0x0088)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_3;                   // 0x0FB0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_18;                             // 0x1038(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_7;                    // 0x1058(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_6;                    // 0x1098(0x0040)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_5;                    // 0x10D8(0x0040)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_2;                   // 0x1118(0x0088)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool_1;                   // 0x11A0(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root_17;                             // 0x1228(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_10;                  // 0x1248(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_16;                             // 0x1310(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_4;                    // 0x1330(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_15;                             // 0x1370(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_3;                    // 0x1390(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_14;                             // 0x13D0(0x0020)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_2;                    // 0x13F0(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root_13;                             // 0x1430(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_12;                             // 0x1450(0x0020)()
	struct FAnimNode_Root                         AnimGraphNode_Root_11;                             // 0x1470(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_9;                   // 0x1490(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_10;                             // 0x1558(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_8;                   // 0x1578(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_9;                              // 0x1640(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_7;                   // 0x1660(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_8;                              // 0x1728(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_6;                   // 0x1748(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_7;                              // 0x1810(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_5;                   // 0x1830(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_6;                              // 0x18F8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_4;                   // 0x1918(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_5;                              // 0x19E0(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_3;                   // 0x1A00(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_4;                              // 0x1AC8(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_2;                   // 0x1AE8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_3;                              // 0x1BB0(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose_1;                   // 0x1BD0(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_2;                              // 0x1C98(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_LinkedInputPose;                     // 0x1CB8(0x00C8)()
	struct FAnimNode_Root                         AnimGraphNode_Root_1;                              // 0x1D80(0x0020)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_SubInput;                            // 0x1DA0(0x00C8)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer_1;                    // 0x1E68(0x0040)()
	struct FAnimNode_BlendListByBool              AnimGraphNode_BlendListByBool;                     // 0x1EA8(0x0088)()
	struct FAnimNode_SequencePlayer               AnimGraphNode_SequencePlayer;                      // 0x1F30(0x0040)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x1F70(0x0020)()

public:
	void AnimGraph(struct FPoseLink* AnimGraph_0);
	void ExecuteUbergraph_AshtonIndigoLayerAnimBP(int32 EntryPoint);
	void ItemAimOffset(const struct FPoseLink& InPose_AimOffset, float AimOffsetAlpha, float Yaw, float Pitch, const struct FPoseLink& InPose_UpperLowerPreMeleeAO, struct FPoseLink* ItemAimOffset_0);
	void ItemCrouchTurningAdditive(struct FPoseLink* ItemCrouchTurningAdditive_0);
	void ItemFallAdditive(struct FPoseLink* ItemFallAdditive_0);
	void ItemFallLandAdditive(struct FPoseLink* ItemFallLandAdditive_0);
	void ItemFlyModeLoopAdditive(struct FPoseLink* ItemFlyModeLoopAdditive_0);
	void ItemFlyModeStartAdditive(struct FPoseLink* ItemFlyModeStartAdditive_0);
	void ItemFullBodyOverride(const struct FPoseLink& InPoseFullBody, struct FPoseLink* ItemFullBodyOverride_0);
	void ItemFullBodySprint(const struct FPoseLink& InPoseSprint, struct FPoseLink* ItemFullBodySprint_0);
	void ItemIdleAdditive(const struct FPoseLink& InPoseIdleAdditive, struct FPoseLink* ItemIdleAdditive_0);
	void ItemJetPackJumpAdditive(struct FPoseLink* ItemJetPackJumpAdditive_0);
	void ItemJetPackStartAdditive(struct FPoseLink* ItemJetPackStartAdditive_0);
	void ItemJogPostPivotAdditive(const struct FPoseLink& InPosePostPivotAdditive, struct FPoseLink* ItemJogPostPivotAdditive_0);
	void ItemJogPrePivotAdditive(const struct FPoseLink& InPosePrePivotAdditive, struct FPoseLink* ItemJogPrePivotAdditive_0);
	void ItemJogStartAdditive(const struct FPoseLink& InPoseJogStartAdditive, struct FPoseLink* ItemJogStartAdditive_0);
	void ItemJogStopAdditive(const struct FPoseLink& InPoseJogStopAdditive, struct FPoseLink* ItemJogStopAdditive_0);
	void ItemJumpLoopAdditive(struct FPoseLink* ItemJumpLoopAdditive_0);
	void ItemJumpUpAdditive(struct FPoseLink* ItemJumpUpAdditive_0);
	void ItemLowerBodyJogPostPivot(const struct FPoseLink& InPoseLowerBodyJogPostPivot, struct FPoseLink* ItemLowerBodyJogPostPivot_0);
	void ItemLowerBodyJogPrePivot(const struct FPoseLink& InPoseLowerBodyJogPrePivot, struct FPoseLink* ItemLowerBodyJogPrePivot_0);
	void ItemLowerBodyJogStart(const struct FPoseLink& InPoseLowerBodyJogStart, struct FPoseLink* ItemLowerBodyJogStart_0);
	void ItemLowerBodyJogStop(const struct FPoseLink& InPoseLowerBodyJogStop, struct FPoseLink* ItemLowerBodyJogStop_0);
	void ItemLowerBodyLeanAdditive(const struct FPoseLink& InPoseLowerBodyLeanAdditive, struct FPoseLink* ItemLowerBodyLeanAdditive_0);
	void ItemLowerBodyMovement(const struct FPoseLink& InPoseLowerBodyMovement, struct FPoseLink* ItemLowerBodyMovement_0);
	void ItemPreIK(const struct FPoseLink& InPose_PreIK, struct FPoseLink* ItemPreIK_0);
	void ItemRelaxedEntry(const struct FPoseLink& InPoseRelaxedEntry, struct FPoseLink* ItemRelaxedEntry_0);
	void ItemSkeletalControl(const struct FPoseLink& InPose, struct FPoseLink* ItemSkeletalControl_0);
	void ItemSlopeSliding(struct FPoseLink* ItemSlopeSliding_0);
	void ItemSwimJumpFallLoop(struct FPoseLink* ItemSwimJumpFallLoop_0);
	void ItemSwimJumpStart(struct FPoseLink* ItemSwimJumpStart_0);
	void ItemSwimJumpStartLoop(struct FPoseLink* ItemSwimJumpStartLoop_0);
	void ItemSwimJumpSurfaceEnd(struct FPoseLink* ItemSwimJumpSurfaceEnd_0);
	void ItemSwimJumpSurfaceLoop(struct FPoseLink* ItemSwimJumpSurfaceLoop_0);
	void ItemUpperBody(const struct FPoseLink& InPoseUpperBody, const struct FFortAnimInput_AdjustedAim& InputParam, struct FPoseLink* ItemUpperBody_0);
	void ItemZipLineStartAdditive(struct FPoseLink* ItemZipLineStartAdditive_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AshtonIndigoLayerAnimBP_C">();
	}
	static class UAshtonIndigoLayerAnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAshtonIndigoLayerAnimBP_C>();
	}
};

}

