#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaCustomizationPicker

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "SlateCore_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaCustomizationPicker.AthenaCustomizationPicker_C
// 0x00A0 (0x0518 - 0x0478)
class UAthenaCustomizationPicker_C final : public UAthenaCustomizationPicker
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0478(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Contract;                                          // 0x0480(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Expand;                                            // 0x0488(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UPanelButton_C*                         Button_TextSearch;                                 // 0x0490(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFilteredTextEntryWidget_C*             EditableText_Search;                               // 0x0498(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SizeBox_TextSearch;                                // 0x04A0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonTextBlock*                       Text_FilterName;                                   // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonRichTextBlock*                   TextBlock_NoItemAvailable;                         // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_SearchBar;                             // 0x04B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        WidgetSwitcher_DisplayItemAvailability;            // 0x04C0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	TMulticastInlineDelegate<void()>              OnDisableSaveButton;                               // 0x04C8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void()>              OnEnableSaveButton;                                // 0x04D8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	TMulticastInlineDelegate<void(bool bIsSelected)> OnTextSearchSelectedChanged;                    // 0x04E8(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class UAthenaCustomizationPickerTileButton_C* TileButton;                                        // 0x04F8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimerHandle                           TextEntryTimer;                                    // 0x0500(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	TMulticastInlineDelegate<void(class FText NewText)> OnTextChanged;                               // 0x0508(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_AthenaCustomizationPicker(int32 EntryPoint);
	void On_Text_Committed(const class FText& Text, ETextCommit CommitMethod);
	void BndEvt__Button_TextSearch_K2Node_ComponentBoundEvent_0_CommonButtonClicked__DelegateSignature(class UCommonButton* Button);
	void HandleDifferentFilterSetBP();
	void HandleTextChanged(const class FText& Text);
	void OnInitialized();
	void OnSearchEnabled(bool bEnabled);
	void OnItemsAvailableInFilter();
	void OnNoItemsAvailableInFilter(const class FText& EmptyDisplayText);
	void SetTextFilter(const class FText& InText, bool Clear);
	void SetTextFilterSelectedState(bool bIsSelected);
	void GetTextFilterSelectedState(bool* bIsSelected);
	void HandleSearchTextFilterChanged(const class FText& Text);
	void HandleTextEntryTimer();
	void ResetTextSearchFilter();
	void NavigateDownFromSearch(EUINavigation Navigation_0, class UWidget** NewParam);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaCustomizationPicker_C">();
	}
	static class UAthenaCustomizationPicker_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaCustomizationPicker_C>();
	}
};
static_assert(alignof(UAthenaCustomizationPicker_C) == 0x000008, "Wrong alignment on UAthenaCustomizationPicker_C");
static_assert(sizeof(UAthenaCustomizationPicker_C) == 0x000518, "Wrong size on UAthenaCustomizationPicker_C");
static_assert(offsetof(UAthenaCustomizationPicker_C, UberGraphFrame) == 0x000478, "Member 'UAthenaCustomizationPicker_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, Contract) == 0x000480, "Member 'UAthenaCustomizationPicker_C::Contract' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, Expand) == 0x000488, "Member 'UAthenaCustomizationPicker_C::Expand' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, Button_TextSearch) == 0x000490, "Member 'UAthenaCustomizationPicker_C::Button_TextSearch' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, EditableText_Search) == 0x000498, "Member 'UAthenaCustomizationPicker_C::EditableText_Search' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, SizeBox_TextSearch) == 0x0004A0, "Member 'UAthenaCustomizationPicker_C::SizeBox_TextSearch' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, Text_FilterName) == 0x0004A8, "Member 'UAthenaCustomizationPicker_C::Text_FilterName' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, TextBlock_NoItemAvailable) == 0x0004B0, "Member 'UAthenaCustomizationPicker_C::TextBlock_NoItemAvailable' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, VerticalBox_SearchBar) == 0x0004B8, "Member 'UAthenaCustomizationPicker_C::VerticalBox_SearchBar' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, WidgetSwitcher_DisplayItemAvailability) == 0x0004C0, "Member 'UAthenaCustomizationPicker_C::WidgetSwitcher_DisplayItemAvailability' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, OnDisableSaveButton) == 0x0004C8, "Member 'UAthenaCustomizationPicker_C::OnDisableSaveButton' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, OnEnableSaveButton) == 0x0004D8, "Member 'UAthenaCustomizationPicker_C::OnEnableSaveButton' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, OnTextSearchSelectedChanged) == 0x0004E8, "Member 'UAthenaCustomizationPicker_C::OnTextSearchSelectedChanged' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, TileButton) == 0x0004F8, "Member 'UAthenaCustomizationPicker_C::TileButton' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, TextEntryTimer) == 0x000500, "Member 'UAthenaCustomizationPicker_C::TextEntryTimer' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPicker_C, OnTextChanged) == 0x000508, "Member 'UAthenaCustomizationPicker_C::OnTextChanged' has a wrong offset!");

}

