#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaCustomizationPickerTileButton

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaCustomizationPickerTileButton.AthenaCustomizationPickerTileButton_C
// 0x0058 (0x0C38 - 0x0BE0)
class UAthenaCustomizationPickerTileButton_C final : public UAthenaCustomizationPickerTileButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BE0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       OnHover;                                           // 0x0BE8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UImage*                                 ExclusiveFill;                                     // 0x0BF0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               ExclusiveWarningOvr;                               // 0x0BF8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UFortLazyImage*                         Image_Equipped;                                    // 0x0C00(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               NullItemOverlay;                                   // 0x0C08(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UWidgetSwitcher*                        RootWidgetSwitcher;                                // 0x0C10(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 UnownedDampen;                                     // 0x0C18(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	bool                                          IsSlottedSomewhere;                                // 0x0C20(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C21[0x7];                                      // 0x0C21(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void(class UWidgetSwitcher* WidgetSwitcher)> PickedButtonHovered;       // 0x0C28(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)

public:
	void ExecuteUbergraph_AthenaCustomizationPickerTileButton(int32 EntryPoint);
	void OnUpdateExclusiveWarning(bool bShouldWarn);
	void OnEquippedStateChanged(bool bEquipped, bool bOnDifferentSlot);
	void OnChangeOwnedState(bool bOwned);
	void BP_OnUnhovered();
	void BP_OnHovered();
	void OnListItemObjectSet(class UObject* ListItemObject);
	void HandleEquippedStateChanged(bool bEquipped, bool bOnDifferentSlot);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaCustomizationPickerTileButton_C">();
	}
	static class UAthenaCustomizationPickerTileButton_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaCustomizationPickerTileButton_C>();
	}
};
static_assert(alignof(UAthenaCustomizationPickerTileButton_C) == 0x000008, "Wrong alignment on UAthenaCustomizationPickerTileButton_C");
static_assert(sizeof(UAthenaCustomizationPickerTileButton_C) == 0x000C38, "Wrong size on UAthenaCustomizationPickerTileButton_C");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, UberGraphFrame) == 0x000BE0, "Member 'UAthenaCustomizationPickerTileButton_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, OnHover) == 0x000BE8, "Member 'UAthenaCustomizationPickerTileButton_C::OnHover' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, ExclusiveFill) == 0x000BF0, "Member 'UAthenaCustomizationPickerTileButton_C::ExclusiveFill' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, ExclusiveWarningOvr) == 0x000BF8, "Member 'UAthenaCustomizationPickerTileButton_C::ExclusiveWarningOvr' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, Image_Equipped) == 0x000C00, "Member 'UAthenaCustomizationPickerTileButton_C::Image_Equipped' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, NullItemOverlay) == 0x000C08, "Member 'UAthenaCustomizationPickerTileButton_C::NullItemOverlay' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, RootWidgetSwitcher) == 0x000C10, "Member 'UAthenaCustomizationPickerTileButton_C::RootWidgetSwitcher' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, UnownedDampen) == 0x000C18, "Member 'UAthenaCustomizationPickerTileButton_C::UnownedDampen' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, IsSlottedSomewhere) == 0x000C20, "Member 'UAthenaCustomizationPickerTileButton_C::IsSlottedSomewhere' has a wrong offset!");
static_assert(offsetof(UAthenaCustomizationPickerTileButton_C, PickedButtonHovered) == 0x000C28, "Member 'UAthenaCustomizationPickerTileButton_C::PickedButtonHovered' has a wrong offset!");

}

