#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaChallengeListEntry_MoreQuestsTimer

#include "Basic.hpp"

#include "AthenaChallengeListEntry_MoreQuestsTimer_classes.hpp"
#include "AthenaChallengeListEntry_MoreQuestsTimer_parameters.hpp"


namespace SDK
{

// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.BP_InitCountdown
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FTimespan&                 InStartTime                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              ChallengeCategory                                      (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::BP_InitCountdown(const struct FTimespan& InStartTime, const struct FGameplayTag& ChallengeCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "BP_InitCountdown");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_BP_InitCountdown Parms{};

	Parms.InStartTime = std::move(InStartTime);
	Parms.ChallengeCategory = std::move(ChallengeCategory);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.BP_OnChallengeInfoSet
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bDisabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::BP_OnChallengeInfoSet(bool bDisabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "BP_OnChallengeInfoSet");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_BP_OnChallengeInfoSet Parms{};

	Parms.bDisabled = bDisabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "BP_OnItemSelectionChanged");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.EndHighlight
// (Event, Public, BlueprintEvent)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::EndHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "EndHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.ExecuteUbergraph_AthenaChallengeListEntry_MoreQuestsTimer
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::ExecuteUbergraph_AthenaChallengeListEntry_MoreQuestsTimer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "ExecuteUbergraph_AthenaChallengeListEntry_MoreQuestsTimer");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_ExecuteUbergraph_AthenaChallengeListEntry_MoreQuestsTimer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "OnMouseEnter");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "OnMouseLeave");

	Params::AthenaChallengeListEntry_MoreQuestsTimer_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeListEntry_MoreQuestsTimer.AthenaChallengeListEntry_MoreQuestsTimer_C.StartHighlight
// (Event, Public, BlueprintEvent)

void UAthenaChallengeListEntry_MoreQuestsTimer_C::StartHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeListEntry_MoreQuestsTimer_C", "StartHighlight");

	UObject::ProcessEvent(Func, nullptr);
}

}

