#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaEventMatchEliminatedGridScreen

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AthenaEventMatchEliminatedGridScreen.AthenaEventMatchEliminatedGridScreen_C
// 0x0010 (0x04D8 - 0x04C8)
class UAthenaEventMatchEliminatedGridScreen_C final : public UAthenaEventMatchEliminatedGridScreenBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04C8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UUniformGridPanel*                      EliminatedPlayersGrid;                             // 0x04D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void BP_OnActivated();
	void Construct();
	void CreateGridWidgets(TArray<class UUserWidget*>* GridWidgets);
	void ExecuteUbergraph_AthenaEventMatchEliminatedGridScreen(int32 EntryPoint);
	void OnTeamEliminated_BP();
	void ResetGrid(TArray<class UUserWidget*>& GridWidgets);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AthenaEventMatchEliminatedGridScreen_C">();
	}
	static class UAthenaEventMatchEliminatedGridScreen_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAthenaEventMatchEliminatedGridScreen_C>();
	}
};

}

