#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaChallengeEmptyQuest

#include "Basic.hpp"

#include "AthenaChallengeEmptyQuest_classes.hpp"
#include "AthenaChallengeEmptyQuest_parameters.hpp"


namespace SDK
{

// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.BP_OnChallengeInfoSet
// (Event, Public, BlueprintEvent)
// Parameters:
// bool                                    bDisabled                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeEmptyQuest_C::BP_OnChallengeInfoSet(bool bDisabled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "BP_OnChallengeInfoSet");

	Params::AthenaChallengeEmptyQuest_C_BP_OnChallengeInfoSet Parms{};

	Parms.bDisabled = bDisabled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.BP_OnItemSelectionChanged
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bIsSelected                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeEmptyQuest_C::BP_OnItemSelectionChanged(bool bIsSelected)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "BP_OnItemSelectionChanged");

	Params::AthenaChallengeEmptyQuest_C_BP_OnItemSelectionChanged Parms{};

	Parms.bIsSelected = bIsSelected;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.EndHighlight
// (Event, Public, BlueprintEvent)

void UAthenaChallengeEmptyQuest_C::EndHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "EndHighlight");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.ExecuteUbergraph_AthenaChallengeEmptyQuest
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaChallengeEmptyQuest_C::ExecuteUbergraph_AthenaChallengeEmptyQuest(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "ExecuteUbergraph_AthenaChallengeEmptyQuest");

	Params::AthenaChallengeEmptyQuest_C_ExecuteUbergraph_AthenaChallengeEmptyQuest Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.OnMouseEnter
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaChallengeEmptyQuest_C::OnMouseEnter(const struct FGeometry& MyGeometry, const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "OnMouseEnter");

	Params::AthenaChallengeEmptyQuest_C_OnMouseEnter Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.OnMouseLeave
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FPointerEvent&             MouseEvent                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void UAthenaChallengeEmptyQuest_C::OnMouseLeave(const struct FPointerEvent& MouseEvent)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "OnMouseLeave");

	Params::AthenaChallengeEmptyQuest_C_OnMouseLeave Parms{};

	Parms.MouseEvent = std::move(MouseEvent);

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaChallengeEmptyQuest.AthenaChallengeEmptyQuest_C.StartHighlight
// (Event, Public, BlueprintEvent)

void UAthenaChallengeEmptyQuest_C::StartHighlight()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaChallengeEmptyQuest_C", "StartHighlight");

	UObject::ProcessEvent(Func, nullptr);
}

}

