#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AthenaSpecialEventStartedOverlay

#include "Basic.hpp"

#include "AthenaSpecialEventStartedOverlay_classes.hpp"
#include "AthenaSpecialEventStartedOverlay_parameters.hpp"


namespace SDK
{

// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.ClearActiveContent
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::ClearActiveContent()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "ClearActiveContent");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.EventAssetsReady
// (BlueprintCallable, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::EventAssetsReady()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "EventAssetsReady");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.ExecuteUbergraph_AthenaSpecialEventStartedOverlay
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::ExecuteUbergraph_AthenaSpecialEventStartedOverlay(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "ExecuteUbergraph_AthenaSpecialEventStartedOverlay");

	Params::AthenaSpecialEventStartedOverlay_C_ExecuteUbergraph_AthenaSpecialEventStartedOverlay Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.OnLoaded_A32BB68840E17C205A4E808089D4FD31
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::OnLoaded_A32BB68840E17C205A4E808089D4FD31(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "OnLoaded_A32BB68840E17C205A4E808089D4FD31");

	Params::AthenaSpecialEventStartedOverlay_C_OnLoaded_A32BB68840E17C205A4E808089D4FD31 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.OnLoaded_A65852ED4A1DB26382C36E9ED70E41B5
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::OnLoaded_A65852ED4A1DB26382C36E9ED70E41B5(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "OnLoaded_A65852ED4A1DB26382C36E9ED70E41B5");

	Params::AthenaSpecialEventStartedOverlay_C_OnLoaded_A65852ED4A1DB26382C36E9ED70E41B5 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.OnLoaded_EC50AB1640470BE09F1297AFEA303108
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Loaded                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::OnLoaded_EC50AB1640470BE09F1297AFEA303108(class UObject* Loaded)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "OnLoaded_EC50AB1640470BE09F1297AFEA303108");

	Params::AthenaSpecialEventStartedOverlay_C_OnLoaded_EC50AB1640470BE09F1297AFEA303108 Parms{};

	Parms.Loaded = Loaded;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.OnPrioitizedFinished
// (Event, Protected, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::OnPrioitizedFinished()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "OnPrioitizedFinished");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.OnShowUrgentQuestMessage
// (Event, Protected, HasOutParams, BlueprintEvent)
// Parameters:
// const struct FUrgentQuestData&          UrgentQuestData                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const float                             EventTimeRemaining                                     (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::OnShowUrgentQuestMessage(const struct FUrgentQuestData& UrgentQuestData, const float EventTimeRemaining)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "OnShowUrgentQuestMessage");

	Params::AthenaSpecialEventStartedOverlay_C_OnShowUrgentQuestMessage Parms{};

	Parms.UrgentQuestData = std::move(UrgentQuestData);
	Parms.EventTimeRemaining = EventTimeRemaining;

	UObject::ProcessEvent(Func, &Parms);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.PlayBountyElimAudio
// (BlueprintCallable, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::PlayBountyElimAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "PlayBountyElimAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.PlayBountyMessageAudio
// (BlueprintCallable, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::PlayBountyMessageAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "PlayBountyMessageAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.PlayMessageAudio
// (Public, BlueprintCallable, BlueprintEvent)

void UAthenaSpecialEventStartedOverlay_C::PlayMessageAudio()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "PlayMessageAudio");

	UObject::ProcessEvent(Func, nullptr);
}


// Function AthenaSpecialEventStartedOverlay.AthenaSpecialEventStartedOverlay_C.TryUpdateUrgentAlertIcon
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          AlertIcon                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector2D&                 AlertIconBrushSize                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FLinearColor&              AlertIconBorderColor                                   (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UAthenaSpecialEventStartedOverlay_C::TryUpdateUrgentAlertIcon(class UObject* AlertIcon, const struct FVector2D& AlertIconBrushSize, const struct FLinearColor& AlertIconBorderColor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("AthenaSpecialEventStartedOverlay_C", "TryUpdateUrgentAlertIcon");

	Params::AthenaSpecialEventStartedOverlay_C_TryUpdateUrgentAlertIcon Parms{};

	Parms.AlertIcon = AlertIcon;
	Parms.AlertIconBrushSize = std::move(AlertIconBrushSize);
	Parms.AlertIconBorderColor = std::move(AlertIconBorderColor);

	UObject::ProcessEvent(Func, &Parms);
}

}

