#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AudioGameplay

#include "Basic.hpp"

#include "Engine_classes.hpp"
#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class AudioGameplay.AudioGameplayComponent
// 0x0008 (0x00B8 - 0x00B0)
class UAudioGameplayComponent : public UActorComponent
{
public:
	uint8                                         Pad_B0[0x8];                                       // 0x00B0(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayComponent">();
	}
	static class UAudioGameplayComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAudioGameplayComponent>();
	}
};

// Class AudioGameplay.AudioGameplayCondition
// 0x0000 (0x0000 - 0x0000)
class IAudioGameplayCondition final
{
public:
	bool ConditionMet() const;
	bool ConditionMet_Position(const struct FVector& Position) const;

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayCondition">();
	}
	static class IAudioGameplayCondition* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioGameplayCondition>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

// Class AudioGameplay.AudioGameplayVolumeInteraction
// 0x0000 (0x0000 - 0x0000)
class IAudioGameplayVolumeInteraction final
{
public:
	void OnListenerEnter();
	void OnListenerExit();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"AudioGameplayVolumeInteraction">();
	}
	static class IAudioGameplayVolumeInteraction* GetDefaultObj()
	{
		return GetDefaultObjImpl<IAudioGameplayVolumeInteraction>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

