#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AutoRunHUDWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass AutoRunHUDWidget.AutoRunHUDWidget_C
// 0x0010 (0x02C0 - 0x02B0)
class UAutoRunHUDWidget_C final : public UFortHUDElementWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 Image_Run;                                         // 0x02B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnAutoRunEnabled_Bind(bool bAutoRunEnabled);
	void ExecuteUbergraph_AutoRunHUDWidget(int32 EntryPoint);
	void Destruct();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"AutoRunHUDWidget_C">();
	}
	static class UAutoRunHUDWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UAutoRunHUDWidget_C>();
	}
};

}

