#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Artemis_FlopperSpawnWorld_Placement

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "GameplayTags_structs.hpp"
#include "GameplayAbilities_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "AIModule_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Artemis_FlopperSpawnWorld_Placement.B_Artemis_FlopperSpawnWorld_Placement_C
// 0x0250 (0x0470 - 0x0220)
class AB_Artemis_FlopperSpawnWorld_Placement_C final : public AActor
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0220(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UBillboardComponent*                    Billboard;                                         // 0x0228(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	class USceneComponent*                        DefaultSceneRoot;                                  // 0x0230(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         HeightOffset;                                      // 0x0238(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_23C[0x4];                                      // 0x023C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FScalableFloat                         Row_Enabled;                                       // 0x0240(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_SpawnChanceMin;                                // 0x0268(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         Row_SpawnChanceMax;                                // 0x0290(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         AmountSpawned;                                     // 0x02B8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2BC[0x4];                                      // 0x02BC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<struct FVector>                        WaterBodyLocationsToSpawn;                         // 0x02C0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         DistanceBetweenSpawnsRiverNarrow;                  // 0x02D0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RiverNarrowSpawnOffset;                            // 0x02D4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AArtemis_Waterbody_River_Parent_C*> RiversNarrow;                                   // 0x02D8(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	float                                         DistanceBetweenSpawnsRiverWide;                    // 0x02E8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         RiverWideSpawnOffset;                              // 0x02EC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AArtemis_Waterbody_River_Parent_C*> RiversWide;                                     // 0x02F0(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	float                                         DistanceBetweenSpawnsLake;                         // 0x0300(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         LakeSpawnOffset;                                   // 0x0304(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AArtemis_Waterbody_Lake_Parent_C*> Lakes;                                           // 0x0308(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	float                                         DistanceBetweenSpawnsIsland;                       // 0x0318(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         IslandSpawnOffset;                                 // 0x031C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AArtemis_Waterbody_Island_Parent_C*> Island;                                        // 0x0320(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	float                                         DistanceBetweenSpawnsOceanIsland;                  // 0x0330(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OceanIslandSpawnOffset;                            // 0x0334(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AWaterBodyIsland*>               OceansIslands;                                     // 0x0338(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	float                                         InitialSpawnVarience;                              // 0x0348(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         SplineLength;                                      // 0x034C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         InitialDistanceOnSpline;                           // 0x0350(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         DistanceBetweenSpawnsCustomSpline;                 // 0x0354(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         CustomSplineSpawnOffset;                           // 0x0358(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_35C[0x4];                                      // 0x035C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	TArray<class AB_FlopperSpawn_CustomSpline_C*> CustomSpawnerSpline;                               // 0x0360(0x0010)(Edit, BlueprintVisible, DisableEditOnTemplate)
	TMap<struct FGameplayTag, class UClass*>      POI_SpawnerMap;                                    // 0x0370(0x0050)(Edit, BlueprintVisible, DisableEditOnInstance)
	class UClass*                                 FlopperSpawner;                                    // 0x03C0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UEnvQueryInstanceBlueprintWrapper*      QueryInstance;                                     // 0x03C8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<struct FVector>                        FloodLocationsToSpawn;                             // 0x03D0(0x0010)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         WaterBodyAmountSpawned;                            // 0x03E0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         OceanHeight;                                       // 0x03E4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         GridSize;                                          // 0x03E8(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	struct FScalableFloat                         SpaceBetween;                                      // 0x0410(0x0028)(Edit, BlueprintVisible, DisableEditOnInstance)
	uint8                                         Pad_438[0x8];                                      // 0x0438(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTransform                             SpawnPoint;                                        // 0x0440(0x0030)(Edit, BlueprintVisible, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	void StartWaterBodySpawn();
	void StartEQSSpawn();
	void Spawn(const struct FTransform& SpawnTransform, int32 ItemIndex);
	void RollRarity(EFortRarity* RarityOut);
	void ReceiveBeginPlay();
	void OnReady_FDC1A68B4F1D24CA5D5C0EB7F4616663(class AFortGameStateAthena* GameState, const class UFortPlaylist* Playlist, const struct FGameplayTagContainer& PlaylistContextTags);
	struct FVector GetNormal(class USplineComponent* Spline, float Distance);
	void FindRiverWideLocations();
	void FindRiverNarrowLocations();
	void FindOceanLocations();
	void FindLakeLocations();
	void FindIslandLocations();
	void FindCustomSplineLocations();
	void ExecuteUbergraph_B_Artemis_FlopperSpawnWorld_Placement(int32 EntryPoint);
	void EQS_Finished(class UEnvQueryInstanceBlueprintWrapper* QueryInstance_0, EEnvQueryStatus QueryStatus);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Artemis_FlopperSpawnWorld_Placement_C">();
	}
	static class AB_Artemis_FlopperSpawnWorld_Placement_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Artemis_FlopperSpawnWorld_Placement_C>();
	}
};

}

