#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Assault_RedDotAR_Athena_Weap

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Assault_RedDotAR_Athena_Weap.B_Assault_RedDotAR_Athena_Weap_C
// 0x0078 (0x1B28 - 0x1AB0)
class AB_Assault_RedDotAR_Athena_Weap_C final : public AB_Ranged_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_Assault_RedDotAR_Athena_Weap_C;   // 0x1AB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         FireShake_NewTrack_0_4091D9F74733732BAF3EBDA884D51155; // 0x1AB8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            FireShake__Direction_4091D9F74733732BAF3EBDA884D51155; // 0x1ABC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1ABD[0x3];                                     // 0x1ABD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     FireShake;                                         // 0x1AC0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ADS_NewTrack_0_6C56679048DB47AA0F4D0CB042747FC7;   // 0x1AC8(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            ADS__Direction_6C56679048DB47AA0F4D0CB042747FC7;   // 0x1ACC(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1ACD[0x3];                                     // 0x1ACD(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Ads;                                               // 0x1AD0(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         Firing_Rate;                                       // 0x1AD8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         XOffset;                                           // 0x1ADC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         YOffset;                                           // 0x1AE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         PreADSYOffset;                                     // 0x1AE4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FRotator                               PreviousRotation;                                  // 0x1AE8(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	float                                         PreADSXOffset;                                     // 0x1AF4(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         YOffsetInterpTarget;                               // 0x1AF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         XOffsetInterpTarget;                               // 0x1AFC(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         YADSOffset;                                        // 0x1B00(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         XADSOffset;                                        // 0x1B04(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         ADSAlpha;                                          // 0x1B08(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         XStrafeOffset;                                     // 0x1B0C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         YRecoilOffset;                                     // 0x1B10(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         XRecoilOffset;                                     // 0x1B14(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          Firing;                                            // 0x1B18(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1B19[0x7];                                     // 0x1B19(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FTimerHandle                           RecoilTimerHandle;                                 // 0x1B20(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)

public:
	void ADS__FinishedFunc();
	void ADS__UpdateFunc();
	void ExecuteUbergraph_B_Assault_RedDotAR_Athena_Weap(int32 EntryPoint);
	void FireShake__FinishedFunc();
	void FireShake__UpdateFunc();
	void OnPlayWeaponFireFX(bool bPersistentFire, bool bSecondaryFire);
	void OnSetTargeting(bool bNewIsTargeting);
	void OnStopWeaponFireFX();
	void ReceiveBeginPlay();
	void ReceiveTick(float DeltaSeconds);
	void RecoilCamShake();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Assault_RedDotAR_Athena_Weap_C">();
	}
	static class AB_Assault_RedDotAR_Athena_Weap_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Assault_RedDotAR_Athena_Weap_C>();
	}
};

}

