#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_FringePlank_Generic_Athena

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_FringePlank_Generic_Athena.B_FringePlank_Generic_Athena_C
// 0x0010 (0x1AC0 - 0x1AB0)
class AB_FringePlank_Generic_Athena_C final : public AB_Ranged_Generic_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_B_FringePlank_Generic_Athena_C;     // 0x1AB0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UParticleSystemComponent*               RearMuzzle;                                        // 0x1AB8(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_B_FringePlank_Generic_Athena(int32 EntryPoint);
	void K2_OnUnEquip();
	void Muzzle_Flash_FX(bool Persistent_Fire);
	void OnAmmoCountChanged();
	void RepAmmoCountChangedGarbage();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_FringePlank_Generic_Athena_C">();
	}
	static class AB_FringePlank_Generic_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_FringePlank_Generic_Athena_C>();
	}
};

}

