#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: B_Hookgun_Athena

#include "Basic.hpp"

#include "B_Ranged_Generic_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass B_Hookgun_Athena.B_Hookgun_Athena_C
// 0x0000 (0x12A8 - 0x12A8)
class AB_Hookgun_Athena_C final : public AB_Ranged_Generic_C
{
public:
	bool                                          Debug;                                             // 0x12A4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"B_Hookgun_Athena_C">();
	}
	static class AB_Hookgun_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AB_Hookgun_Athena_C>();
	}
};
static_assert(alignof(AB_Hookgun_Athena_C) == 0x000008, "Wrong alignment on AB_Hookgun_Athena_C");
static_assert(sizeof(AB_Hookgun_Athena_C) == 0x0012A8, "Wrong size on AB_Hookgun_Athena_C");
static_assert(offsetof(AB_Hookgun_Athena_C, Debug) == 0x0012A4, "Member 'AB_Hookgun_Athena_C::Debug' has a wrong offset!");

}

