#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BGA_Athena_SidewaysEncounter_BubbleSmall

#include "Basic.hpp"

#include "BGA_Athena_SidewaysEncounter_BubbleSmall_classes.hpp"
#include "BGA_Athena_SidewaysEncounter_BubbleSmall_parameters.hpp"


namespace SDK
{

// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    bFromSweep                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                SweepResult                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex, bool bFromSweep, const struct FHitResult& SweepResult)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_3_ComponentBeginOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;
	Parms.bFromSweep = bFromSweep;
	Parms.SweepResult = std::move(SweepResult);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_4_ComponentEndOverlapSignature__DelegateSignature
// (BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              OverlappedComponent                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// int32                                   OtherBodyIndex                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_4_ComponentEndOverlapSignature__DelegateSignature(class UPrimitiveComponent* OverlappedComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, int32 OtherBodyIndex)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_4_ComponentEndOverlapSignature__DelegateSignature");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_BndEvt__BuildBlockingVolume_K2Node_ComponentBoundEvent_4_ComponentEndOverlapSignature__DelegateSignature Parms{};

	Parms.OverlappedComponent = OverlappedComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.OtherBodyIndex = OtherBodyIndex;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.BndEvt__EncounterEdge_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature
// (HasOutParams, BlueprintEvent)
// Parameters:
// class UPrimitiveComponent*              HitComponent                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UPrimitiveComponent*              OtherComp                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FVector&                   NormalImpulse                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                Hit                                                    (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::BndEvt__EncounterEdge_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature(class UPrimitiveComponent* HitComponent, class AActor* OtherActor, class UPrimitiveComponent* OtherComp, const struct FVector& NormalImpulse, const struct FHitResult& Hit)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "BndEvt__EncounterEdge_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_BndEvt__EncounterEdge_K2Node_ComponentBoundEvent_0_ComponentHitSignature__DelegateSignature Parms{};

	Parms.HitComponent = HitComponent;
	Parms.OtherActor = OtherActor;
	Parms.OtherComp = OtherComp;
	Parms.NormalImpulse = std::move(NormalImpulse);
	Parms.Hit = std::move(Hit);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.Destroy Buildings
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   EndScale                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// float                                   ScaleDuration                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::Destroy_Buildings(float EndScale, float ScaleDuration)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "Destroy Buildings");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_Destroy_Buildings Parms{};

	Parms.EndScale = EndScale;
	Parms.ScaleDuration = ScaleDuration;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.DestroyBuildingsFromTimer
// (Private, HasDefaults, BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::DestroyBuildingsFromTimer()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "DestroyBuildingsFromTimer");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.EncounterBeaten
// (BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::EncounterBeaten()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "EncounterBeaten");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.EncounterStageCompleted
// (BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::EncounterStageCompleted()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "EncounterStageCompleted");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.ExecuteUbergraph_BGA_Athena_SidewaysEncounter_BubbleSmall
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::ExecuteUbergraph_BGA_Athena_SidewaysEncounter_BubbleSmall(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "ExecuteUbergraph_BGA_Athena_SidewaysEncounter_BubbleSmall");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_ExecuteUbergraph_BGA_Athena_SidewaysEncounter_BubbleSmall Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.GetSidewaysPlayspace
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// class ASmallSidewaysPlayspace_C**       Playspace                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::GetSidewaysPlayspace(class ASmallSidewaysPlayspace_C** Playspace)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "GetSidewaysPlayspace");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_GetSidewaysPlayspace Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (Playspace != nullptr)
		*Playspace = Parms.Playspace;
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.HandleReplayScrubStart
// (BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::HandleReplayScrubStart()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "HandleReplayScrubStart");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.OnDamagePlayEffects
// (BlueprintCosmetic, Event, Public, HasOutParams, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTagContainer&     DamageTags                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const struct FVector&                   Momentum                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FHitResult&                HitInfo                                                (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AFortPawn*                        InstigatedBy                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayEffectContextHandle&EffectContext                                          (BlueprintVisible, BlueprintReadOnly, Parm)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::OnDamagePlayEffects(float Damage, const struct FGameplayTagContainer& DamageTags, const struct FVector& Momentum, const struct FHitResult& HitInfo, class AFortPawn* InstigatedBy, class AActor* DamageCauser, const struct FGameplayEffectContextHandle& EffectContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "OnDamagePlayEffects");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_OnDamagePlayEffects Parms{};

	Parms.Damage = Damage;
	Parms.DamageTags = std::move(DamageTags);
	Parms.Momentum = std::move(Momentum);
	Parms.HitInfo = std::move(HitInfo);
	Parms.InstigatedBy = InstigatedBy;
	Parms.DamageCauser = DamageCauser;
	Parms.EffectContext = std::move(EffectContext);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.OnRep_BubbleVisible
// (BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::OnRep_BubbleVisible()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "OnRep_BubbleVisible");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.PawnEnterBubble
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   EnterLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::PawnEnterBubble(const struct FVector& EnterLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "PawnEnterBubble");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_PawnEnterBubble Parms{};

	Parms.EnterLocation = std::move(EnterLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.PawnExitBubble
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   EnterLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::PawnExitBubble(const struct FVector& EnterLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "PawnExitBubble");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_PawnExitBubble Parms{};

	Parms.EnterLocation = std::move(EnterLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.ShouldDie
// (BlueprintAuthorityOnly, Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   Damage                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AController*                      EventInstigator                                        (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           DamageCauser                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool ABGA_Athena_SidewaysEncounter_BubbleSmall_C::ShouldDie(float Damage, class AController* EventInstigator, class AActor* DamageCauser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "ShouldDie");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_ShouldDie Parms{};

	Parms.Damage = Damage;
	Parms.EventInstigator = EventInstigator;
	Parms.DamageCauser = DamageCauser;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.ThingsHitBubble
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FHitResult&                Hit                                                    (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor, ContainsInstancedReference)
// class AActor*                           OtherActor                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::ThingsHitBubble(const struct FHitResult& Hit, class AActor* OtherActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "ThingsHitBubble");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_ThingsHitBubble Parms{};

	Parms.Hit = std::move(Hit);
	Parms.OtherActor = OtherActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.UserConstructionScript
// (Event, Public, BlueprintCallable, BlueprintEvent)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::UserConstructionScript()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "UserConstructionScript");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.VehicleEnterBubble
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   EnterLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::VehicleEnterBubble(const struct FVector& EnterLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "VehicleEnterBubble");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_VehicleEnterBubble Parms{};

	Parms.EnterLocation = std::move(EnterLocation);

	UObject::ProcessEvent(Func, &Parms);
}


// Function BGA_Athena_SidewaysEncounter_BubbleSmall.BGA_Athena_SidewaysEncounter_BubbleSmall_C.VehicleExitBubble
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FVector&                   EnterLocation                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABGA_Athena_SidewaysEncounter_BubbleSmall_C::VehicleExitBubble(const struct FVector& EnterLocation)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BGA_Athena_SidewaysEncounter_BubbleSmall_C", "VehicleExitBubble");

	Params::BGA_Athena_SidewaysEncounter_BubbleSmall_C_VehicleExitBubble Parms{};

	Parms.EnterLocation = std::move(EnterLocation);

	UObject::ProcessEvent(Func, &Parms);
}

}

