#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_AthenaCollectionScreenContainer

#include "Basic.hpp"

#include "BP_AthenaCollectionScreenContainer_classes.hpp"
#include "BP_AthenaCollectionScreenContainer_parameters.hpp"


namespace SDK
{

// Function BP_AthenaCollectionScreenContainer.BP_AthenaCollectionScreenContainer_C.BP_OnShowTabsSet
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bShowTabs                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionScreenContainer_C::BP_OnShowTabsSet(bool bShowTabs)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionScreenContainer_C", "BP_OnShowTabsSet");

	Params::BP_AthenaCollectionScreenContainer_C_BP_OnShowTabsSet Parms{};

	Parms.bShowTabs = bShowTabs;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionScreenContainer.BP_AthenaCollectionScreenContainer_C.ExecuteUbergraph_BP_AthenaCollectionScreenContainer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionScreenContainer_C::ExecuteUbergraph_BP_AthenaCollectionScreenContainer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionScreenContainer_C", "ExecuteUbergraph_BP_AthenaCollectionScreenContainer");

	Params::BP_AthenaCollectionScreenContainer_C_ExecuteUbergraph_BP_AthenaCollectionScreenContainer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_AthenaCollectionScreenContainer.BP_AthenaCollectionScreenContainer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBP_AthenaCollectionScreenContainer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_AthenaCollectionScreenContainer_C", "PreConstruct");

	Params::BP_AthenaCollectionScreenContainer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

