#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Campfire_Interface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Campfire_Interface.Campfire_Interface_C
// 0x0000 (0x0000 - 0x0000)
class ICampfire_Interface_C final
{
public:
	void IsStoked(bool* IsStoked_0);
	void GetWoodComponent(class UStaticMeshComponent** WoodComponent);
	void GetLocationToSpawnFireVFX(struct FVector* WorldLocation);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Campfire_Interface_C">();
	}
	static class ICampfire_Interface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ICampfire_Interface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

