#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Car_PartyBus_Ground

#include "Basic.hpp"

#include "Car_DEFAULT_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Car_PartyBus_Ground.Car_PartyBus_Ground_C
// 0x0000 (0x0F40 - 0x0F40)
class ACar_PartyBus_Ground_C final : public ACar_DEFAULT_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Car_PartyBus_Ground_C">();
	}
	static class ACar_PartyBus_Ground_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ACar_PartyBus_Ground_C>();
	}
};

}

