#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: DynamicHUDTestUI

#include "Basic.hpp"


namespace SDK::Params
{

// Function DynamicHUDTestUI.DynamicHUDTestUIDirector.AddScene
// 0x0008 (0x0008 - 0x0000)
struct DynamicHUDTestUIDirector_AddScene final
{
public:
	const class UDynamicHUDScene*                 Scene;                                             // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DynamicHUDTestUIDirector_AddScene) == 0x000008, "Wrong alignment on DynamicHUDTestUIDirector_AddScene");
static_assert(sizeof(DynamicHUDTestUIDirector_AddScene) == 0x000008, "Wrong size on DynamicHUDTestUIDirector_AddScene");
static_assert(offsetof(DynamicHUDTestUIDirector_AddScene, Scene) == 0x000000, "Member 'DynamicHUDTestUIDirector_AddScene::Scene' has a wrong offset!");

// Function DynamicHUDTestUI.DynamicHUDTestUIDirector.RemoveScene
// 0x0008 (0x0008 - 0x0000)
struct DynamicHUDTestUIDirector_RemoveScene final
{
public:
	const class UDynamicHUDScene*                 Scene;                                             // 0x0000(0x0008)(ConstParm, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DynamicHUDTestUIDirector_RemoveScene) == 0x000008, "Wrong alignment on DynamicHUDTestUIDirector_RemoveScene");
static_assert(sizeof(DynamicHUDTestUIDirector_RemoveScene) == 0x000008, "Wrong size on DynamicHUDTestUIDirector_RemoveScene");
static_assert(offsetof(DynamicHUDTestUIDirector_RemoveScene, Scene) == 0x000000, "Member 'DynamicHUDTestUIDirector_RemoveScene::Scene' has a wrong offset!");

// Function DynamicHUDTestUI.DynamicHUDUIWidget.OnUpdateMessage
// 0x0010 (0x0010 - 0x0000)
struct DynamicHUDUIWidget_OnUpdateMessage final
{
public:
	class FString                                 NewMessage;                                        // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
};
static_assert(alignof(DynamicHUDUIWidget_OnUpdateMessage) == 0x000008, "Wrong alignment on DynamicHUDUIWidget_OnUpdateMessage");
static_assert(sizeof(DynamicHUDUIWidget_OnUpdateMessage) == 0x000010, "Wrong size on DynamicHUDUIWidget_OnUpdateMessage");
static_assert(offsetof(DynamicHUDUIWidget_OnUpdateMessage, NewMessage) == 0x000000, "Member 'DynamicHUDUIWidget_OnUpdateMessage::NewMessage' has a wrong offset!");

}

