#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Entity_Physics_HitResult

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass Entity_Physics_HitResult.HitResult
// 0x0020 (0x0048 - 0x0028)
class UHitResult final : public UObject
{
public:
	int32                                         __verse_0x592C3A0F_OtherEntityID;                  // 0x0028(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_2C[0x4];                                       // 0x002C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UEntityActorCollisionComponent*         __verse_0x15DAA648_OtherComponent;                 // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVector3*                               __verse_0xA0175DA6_HitNormal;                      // 0x0038(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVector3*                               __verse_0xE16733E1_HitLocation;                    // 0x0040(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"HitResult">();
	}
	static class UHitResult* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHitResult>();
	}
};
static_assert(alignof(UHitResult) == 0x000008, "Wrong alignment on UHitResult");
static_assert(sizeof(UHitResult) == 0x000048, "Wrong size on UHitResult");
static_assert(offsetof(UHitResult, __verse_0x592C3A0F_OtherEntityID) == 0x000028, "Member 'UHitResult::__verse_0x592C3A0F_OtherEntityID' has a wrong offset!");
static_assert(offsetof(UHitResult, __verse_0x15DAA648_OtherComponent) == 0x000030, "Member 'UHitResult::__verse_0x15DAA648_OtherComponent' has a wrong offset!");
static_assert(offsetof(UHitResult, __verse_0xA0175DA6_HitNormal) == 0x000038, "Member 'UHitResult::__verse_0xA0175DA6_HitNormal' has a wrong offset!");
static_assert(offsetof(UHitResult, __verse_0xE16733E1_HitLocation) == 0x000040, "Member 'UHitResult::__verse_0xE16733E1_HitLocation' has a wrong offset!");

}

