#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: F_MED_Prime_Skeleton_AnimBlueprint_A

#include "Basic.hpp"

#include "F_MED_Prime_Skeleton_AnimBlueprint_A_classes.hpp"
#include "F_MED_Prime_Skeleton_AnimBlueprint_A_parameters.hpp"


namespace SDK
{

// Function F_MED_Prime_Skeleton_AnimBlueprint_A.F_MED_Prime_Skeleton_AnimBlueprint_A_C.ExecuteUbergraph_F_MED_Prime_Skeleton_AnimBlueprint_A
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_MED_Prime_Skeleton_AnimBlueprint_A_C::ExecuteUbergraph_F_MED_Prime_Skeleton_AnimBlueprint_A(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_MED_Prime_Skeleton_AnimBlueprint_A_C", "ExecuteUbergraph_F_MED_Prime_Skeleton_AnimBlueprint_A");

	Params::F_MED_Prime_Skeleton_AnimBlueprint_A_C_ExecuteUbergraph_F_MED_Prime_Skeleton_AnimBlueprint_A Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function F_MED_Prime_Skeleton_AnimBlueprint_A.F_MED_Prime_Skeleton_AnimBlueprint_A_C.BlueprintUpdateAnimation
// (Event, Public, BlueprintEvent)
// Parameters:
// float                                   DeltaTimeX                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UF_MED_Prime_Skeleton_AnimBlueprint_A_C::BlueprintUpdateAnimation(float DeltaTimeX)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_MED_Prime_Skeleton_AnimBlueprint_A_C", "BlueprintUpdateAnimation");

	Params::F_MED_Prime_Skeleton_AnimBlueprint_A_C_BlueprintUpdateAnimation Parms{};

	Parms.DeltaTimeX = DeltaTimeX;

	UObject::ProcessEvent(Func, &Parms);
}


// Function F_MED_Prime_Skeleton_AnimBlueprint_A.F_MED_Prime_Skeleton_AnimBlueprint_A_C.AnimGraph
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// struct FPoseLink*                       AnimGraph_0                                            (Parm, OutParm, NoDestructor)

void UF_MED_Prime_Skeleton_AnimBlueprint_A_C::AnimGraph(struct FPoseLink* AnimGraph_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("F_MED_Prime_Skeleton_AnimBlueprint_A_C", "AnimGraph");

	Params::F_MED_Prime_Skeleton_AnimBlueprint_A_C_AnimGraph Parms{};

	UObject::ProcessEvent(Func, &Parms);

	if (AnimGraph_0 != nullptr)
		*AnimGraph_0 = std::move(Parms.AnimGraph_0);
}

}

