#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FoodBox_Produce_Athena

#include "Basic.hpp"

#include "Hotfix_Container_Parent_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass FoodBox_Produce_Athena.FoodBox_Produce_Athena_C
// 0x0020 (0x0F58 - 0x0F38)
class AFoodBox_Produce_Athena_C final : public AHotfix_Container_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_FoodBox_Produce_Athena_C;           // 0x0F38(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UArrowComponent*                        LootDropDirection;                                 // 0x0F40(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NonTransactional, NoDestructor, HasGetValueTypeHash)
	float                                         Timeline_0_Time_4EA7087F4D010481DFB08B88C8FF8FEB;  // 0x0F48(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	ETimelineDirection                            Timeline_0__Direction_4EA7087F4D010481DFB08B88C8FF8FEB; // 0x0F4C(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_F4D[0x3];                                      // 0x0F4D(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class UTimelineComponent*                     Timeline_0;                                        // 0x0F50(0x0008)(BlueprintVisible, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_FoodBox_Produce_Athena(int32 EntryPoint);
	void OnLoot();
	void Timeline_0__FinishedFunc();
	void Timeline_0__UpdateFunc();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"FoodBox_Produce_Athena_C">();
	}
	static class AFoodBox_Produce_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<AFoodBox_Produce_Athena_C>();
	}
};

}

