#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_HealSpray_RemoveWhenOutOfAmmo

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_HealSpray_RemoveWhenOutOfAmmo.GA_Athena_HealSpray_RemoveWhenOutOfAmmo_C
// 0x0028 (0x0AD0 - 0x0AA8)
class UGA_Athena_HealSpray_RemoveWhenOutOfAmmo_C final : public UFortGameplayAbility
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AA8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class AFortPlayerPawn*                        FortPawn;                                          // 0x0AB0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class USoundBase*                             OutOfChargesSound;                                 // 0x0AB8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAnimMontage*                           Montage;                                           // 0x0AC0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AB_Athena_HealSpray_C*                  Weapon;                                            // 0x0AC8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_GA_Athena_HealSpray_RemoveWhenOutOfAmmo(int32 EntryPoint);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void OnBlendOut_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void OnCancelled_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void OnCompleted_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void OnInterrupted_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void OnNotifyBegin_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void OnNotifyEnd_011B54574EA14B05D96078B705B18584(const struct FGameplayTag& NotifyTag);
	void RemoveItemAndEndAbility();
	void RemoveWeapon();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_HealSpray_RemoveWhenOutOfAmmo_C">();
	}
	static class UGA_Athena_HealSpray_RemoveWhenOutOfAmmo_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_HealSpray_RemoveWhenOutOfAmmo_C>();
	}
};

}

