#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Athena_Flopper_Zero

#include "Basic.hpp"

#include "GA_Athena_MedConsumable_Parent_classes.hpp"
#include "Engine_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Athena_Flopper_Zero.GA_Athena_Flopper_Zero_C
// 0x0008 (0x0C18 - 0x0C10)
class UGA_Athena_Flopper_Zero_C final : public UGA_Athena_MedConsumable_Parent_C
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame_GA_Athena_Flopper_Zero_C;           // 0x0C10(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GA_Athena_Flopper_Zero(int32 EntryPoint);
	void K2_CommitExecute();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_Athena_Flopper_Zero_C">();
	}
	static class UGA_Athena_Flopper_Zero_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_Athena_Flopper_Zero_C>();
	}
};
static_assert(alignof(UGA_Athena_Flopper_Zero_C) == 0x000008, "Wrong alignment on UGA_Athena_Flopper_Zero_C");
static_assert(sizeof(UGA_Athena_Flopper_Zero_C) == 0x000C18, "Wrong size on UGA_Athena_Flopper_Zero_C");
static_assert(offsetof(UGA_Athena_Flopper_Zero_C, UberGraphFrame_GA_Athena_Flopper_Zero_C) == 0x000C10, "Member 'UGA_Athena_Flopper_Zero_C::UberGraphFrame_GA_Athena_Flopper_Zero_C' has a wrong offset!");

}

