#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_BoostJumpPack

#include "Basic.hpp"

#include "FortniteGame_structs.hpp"
#include "FortniteGame_classes.hpp"
#include "GameplayAbilities_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "Engine_structs.hpp"
#include "GameplayTags_structs.hpp"
#include "Enum_BoostJumpStates_structs.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_BoostJumpPack.GA_BoostJumpPack_C
// 0x01A8 (0x0C80 - 0x0AD8)
class UGA_BoostJumpPack_C : public UFortGameplayAbility_JumpBoostPack
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0AD8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	float                                         Jump_Multiple;                                     // 0x0AE0(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                Basic_Jump_Z_Adjust;                               // 0x0AE4(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                FinalJumpHeight;                                   // 0x0AF0(0x000C)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_AFC[0x4];                                      // 0x0AFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayEventData                     EventTriggerData;                                  // 0x0B00(0x00B0)(Edit, BlueprintVisible, DisableEditOnInstance)
	bool                                          bJumpButtonHeld;                                   // 0x0BB0(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          bAtApex;                                           // 0x0BB1(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BB2[0x2];                                      // 0x0BB2(0x0002)(Fixing Size After Last Property [ Dumper-7 ])
	struct FActiveGameplayEffectHandle            JetpackEffectHandle;                               // 0x0BB4(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BBC[0x4];                                      // 0x0BBC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        FortPlayerPawn;                                    // 0x0BC0(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnTemplate, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         FuelFudge;                                         // 0x0BC8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FActiveGameplayEffectHandle            RegenEffectHandle;                                 // 0x0BCC(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	bool                                          bRegenEffectActive;                                // 0x0BD4(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_BD5[0x3];                                      // 0x0BD5(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  ExecuteTags;                                       // 0x0BD8(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	int32                                         JumpButtonHeldCount;                               // 0x0BF8(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_BFC[0x4];                                      // 0x0BFC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  ReleaseTags;                                       // 0x0C00(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)
	float                                         TimeStartedHovering;                               // 0x0C20(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         TimeStartedFalling;                                // 0x0C24(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EndHoverDelay;                                     // 0x0C28(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EndFallingDelay;                                   // 0x0C2C(0x0004)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          bHasDied;                                          // 0x0C30(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C31[0x3];                                      // 0x0C31(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTag                           BoostCue;                                          // 0x0C34(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	struct FGameplayTag                           BoostJumpPackCue;                                  // 0x0C3C(0x0008)(Edit, BlueprintVisible, DisableEditOnInstance, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C44[0x4];                                      // 0x0C44(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UClass*                                 JetpackInUseEffect;                                // 0x0C48(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UAbilityTask_WaitGameplayTagAdded*      HidingInPropTagTask;                               // 0x0C50(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          TriggeredByJump;                                   // 0x0C58(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C59[0x7];                                      // 0x0C59(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FGameplayTagContainer                  BlockExecuteTags;                                  // 0x0C60(0x0020)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void ExecuteUbergraph_GA_BoostJumpPack(int32 EntryPoint);
	void OnEnterVehicle();
	void OnSavedPawnChanged_(class AFortPlayerPawn* PreviousPawn, class AFortPlayerPawn* NewPawn);
	void Delay_ProcessAbilityStateMachine();
	void OnCurrentStateChanged(EJumpBoostPackState InPreviousState, EJumpBoostPackState InCurrentState);
	void K2_ActivateAbilityFromEvent(const struct FGameplayEventData& EventData);
	void On_Reached_Jump_Apex();
	void OnPawnLanded(const struct FHitResult& Hit);
	void SetJumpHeight(class AFortPlayerPawn* Pawn, class AFortPlayerPawn** Pawn_Out, struct FVector* Jump_Height);
	void HandleBoostJump();
	void SetupTransitionVariables(const struct FGameplayTag& Tag);
	void DetermineStateToTransitionTo(Enum_BoostJumpStates* BoostState);
	void ProcessAbilityStateMachine();
	void TransitionFromBoost(Enum_BoostJumpStates* TargetBoostState);
	void TransitionFromHovering(Enum_BoostJumpStates* TargetBoostState);
	void TransitionFromFalling(Enum_BoostJumpStates* TargetBoostState);
	void ResetTransitionVariables(bool bForceEndHovering);
	void HandleHovering();
	void HandleFalling();
	void HandleIdle(bool bForceEndHovering);
	void Setup_Notify_at_Apex(bool bNotifyApex);
	void PotentiallyEndHovering(bool bForceEndHovering);
	void SetCurrentBoostState(EJumpBoostPackState NewState);
	void HandleCurrentBoostStateChanged(EJumpBoostPackState PreviousState, EJumpBoostPackState CurrentState_0);
	bool IsUsingJetpackEffectActive();
	void Setup_PlayerPawn();
	void K2_OnEndAbility(bool bWasCancelled);
	void Consider_Starting_Regen_Effect();
	void Consider_Stopping_Regen_Effect();
	void Start_Regen_Effect();
	void Stop_Regen_Effect();
	void ProcessTriggerData(const struct FGameplayTag& TagOne);
	void Reset_Toggle_Input_State();
	void OnFuelIsFull();
	void OnFuelIsEmpty();
	void OnAbilityCanceled();
	void SavePlayerPawn();
	void Reengage_Hovering_Movement();
	void Reengage_Falling_Movement();
	void Handle_Jetpack_Equipped();

	void TransitionFromIdle(Enum_BoostJumpStates* TargetBoostState) const;
	void GetFuel(float* Fuel) const;
	void GetMaxFuel(float* MaxFuel) const;
	bool K2_ShouldAbilityRespondToEvent(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayEventData& Payload) const;
	bool IsBoostAllowed() const;
	bool IsCurrentlyDead(const struct FGameplayTag& TagOne) const;
	class AFortPlayerPawn* Get_Player_Pawn(class UObject* Object) const;
	bool Reasons_To_Reset_on_Transition(const struct FGameplayTag& Tag) const;
	bool K2_CanActivateAbility(const struct FGameplayAbilityActorInfo& ActorInfo, const struct FGameplayAbilitySpecHandle& Handle, struct FGameplayTagContainer* RelevantTags) const;
	bool NotInHidingSpot() const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_BoostJumpPack_C">();
	}
	static class UGA_BoostJumpPack_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_BoostJumpPack_C>();
	}
};
static_assert(alignof(UGA_BoostJumpPack_C) == 0x000008, "Wrong alignment on UGA_BoostJumpPack_C");
static_assert(sizeof(UGA_BoostJumpPack_C) == 0x000C80, "Wrong size on UGA_BoostJumpPack_C");
static_assert(offsetof(UGA_BoostJumpPack_C, UberGraphFrame) == 0x000AD8, "Member 'UGA_BoostJumpPack_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, Jump_Multiple) == 0x000AE0, "Member 'UGA_BoostJumpPack_C::Jump_Multiple' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, Basic_Jump_Z_Adjust) == 0x000AE4, "Member 'UGA_BoostJumpPack_C::Basic_Jump_Z_Adjust' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, FinalJumpHeight) == 0x000AF0, "Member 'UGA_BoostJumpPack_C::FinalJumpHeight' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, EventTriggerData) == 0x000B00, "Member 'UGA_BoostJumpPack_C::EventTriggerData' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, bJumpButtonHeld) == 0x000BB0, "Member 'UGA_BoostJumpPack_C::bJumpButtonHeld' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, bAtApex) == 0x000BB1, "Member 'UGA_BoostJumpPack_C::bAtApex' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, JetpackEffectHandle) == 0x000BB4, "Member 'UGA_BoostJumpPack_C::JetpackEffectHandle' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, FortPlayerPawn) == 0x000BC0, "Member 'UGA_BoostJumpPack_C::FortPlayerPawn' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, FuelFudge) == 0x000BC8, "Member 'UGA_BoostJumpPack_C::FuelFudge' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, RegenEffectHandle) == 0x000BCC, "Member 'UGA_BoostJumpPack_C::RegenEffectHandle' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, bRegenEffectActive) == 0x000BD4, "Member 'UGA_BoostJumpPack_C::bRegenEffectActive' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, ExecuteTags) == 0x000BD8, "Member 'UGA_BoostJumpPack_C::ExecuteTags' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, JumpButtonHeldCount) == 0x000BF8, "Member 'UGA_BoostJumpPack_C::JumpButtonHeldCount' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, ReleaseTags) == 0x000C00, "Member 'UGA_BoostJumpPack_C::ReleaseTags' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, TimeStartedHovering) == 0x000C20, "Member 'UGA_BoostJumpPack_C::TimeStartedHovering' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, TimeStartedFalling) == 0x000C24, "Member 'UGA_BoostJumpPack_C::TimeStartedFalling' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, EndHoverDelay) == 0x000C28, "Member 'UGA_BoostJumpPack_C::EndHoverDelay' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, EndFallingDelay) == 0x000C2C, "Member 'UGA_BoostJumpPack_C::EndFallingDelay' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, bHasDied) == 0x000C30, "Member 'UGA_BoostJumpPack_C::bHasDied' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, BoostCue) == 0x000C34, "Member 'UGA_BoostJumpPack_C::BoostCue' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, BoostJumpPackCue) == 0x000C3C, "Member 'UGA_BoostJumpPack_C::BoostJumpPackCue' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, JetpackInUseEffect) == 0x000C48, "Member 'UGA_BoostJumpPack_C::JetpackInUseEffect' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, HidingInPropTagTask) == 0x000C50, "Member 'UGA_BoostJumpPack_C::HidingInPropTagTask' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, TriggeredByJump) == 0x000C58, "Member 'UGA_BoostJumpPack_C::TriggeredByJump' has a wrong offset!");
static_assert(offsetof(UGA_BoostJumpPack_C, BlockExecuteTags) == 0x000C60, "Member 'UGA_BoostJumpPack_C::BlockExecuteTags' has a wrong offset!");

}

