#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_RangedProjectile_FringePlank_Athena

#include "Basic.hpp"

#include "GA_Ranged_GenericProjectileExplosive_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_RangedProjectile_FringePlank_Athena.GA_RangedProjectile_FringePlank_Athena_C
// 0x0000 (0x0AF0 - 0x0AF0)
class UGA_RangedProjectile_FringePlank_Athena_C final : public UGA_Ranged_GenericProjectileExplosive_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GA_RangedProjectile_FringePlank_Athena_C">();
	}
	static class UGA_RangedProjectile_FringePlank_Athena_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGA_RangedProjectile_FringePlank_Athena_C>();
	}
};

}

