#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Athena_Campsite_Tent_Packup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Athena_Campsite_Tent_Packup.GCN_Athena_Campsite_Tent_Packup_C
// 0x0008 (0x01C8 - 0x01C0)
class UGCN_Athena_Campsite_Tent_Packup_C final : public UFortGameplayCueNotify_Burst
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x01C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_GCN_Athena_Campsite_Tent_Packup(int32 EntryPoint);

	void OnBurstGeneric(class AActor* MyTarget, const struct FGameplayCueParameters& Parameters, const TArray<class UFXSystemComponent*>& ParticleComponents, const TArray<class UAudioComponent*>& AudioComponents, class UMatineeCameraShake* BurstCameraShakeInstance, class ADecalActor* BurstDecalInstance) const;

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Athena_Campsite_Tent_Packup_C">();
	}
	static class UGCN_Athena_Campsite_Tent_Packup_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Athena_Campsite_Tent_Packup_C>();
	}
};

}

