#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Cosmos_Rifle_MeleeImpact

#include "Basic.hpp"

#include "CoreUObject_structs.hpp"
#include "GameplayAbilities_structs.hpp"


namespace SDK::Params
{

// Function GCN_Cosmos_Rifle_MeleeImpact.GCN_Cosmos_Rifle_MeleeImpact_C.OnBurstGeneric
// 0x0160 (0x0160 - 0x0000)
struct GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric final
{
public:
	class AActor*                                 MyTarget;                                          // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FGameplayCueParameters                 Parameters;                                        // 0x0008(0x00B8)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference)
	TArray<class UFXSystemComponent*>             ParticleComponents;                                // 0x00C0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	TArray<class UAudioComponent*>                AudioComponents;                                   // 0x00D0(0x0010)(ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, ContainsInstancedReference, HasGetValueTypeHash)
	class UMatineeCameraShake*                    BurstCameraShakeInstance;                          // 0x00E0(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class ADecalActor*                            BurstDecalInstance;                                // 0x00E8(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class APawn*                                  CallFunc_GetPlayerPawn_ReturnValue;                // 0x00F0(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFXSystemComponent*                     CallFunc_Array_Get_Item;                           // 0x00F8(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn;             // 0x0100(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess;                       // 0x0108(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_109[0x7];                                      // 0x0109(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      K2Node_DynamicCast_AsNiagara_Particle_System;      // 0x0110(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_1;                     // 0x0118(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_119[0x7];                                      // 0x0119(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn_1;           // 0x0120(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_2;                     // 0x0128(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_129[0x3];                                      // 0x0129(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	struct FVector                                CallFunc_GetSocketLocation_ReturnValue;            // 0x012C(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FVector                                CallFunc_K2_GetComponentLocation_ReturnValue;      // 0x0138(0x000C)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_144[0x4];                                      // 0x0144(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UNiagaraComponent*                      CallFunc_SpawnSystemAtLocation_ReturnValue;        // 0x0148(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class AFortPlayerPawn*                        K2Node_DynamicCast_AsFort_Player_Pawn_2;           // 0x0150(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_DynamicCast_bSuccess_3;                     // 0x0158(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	bool                                          CallFunc_K2_AttachToComponent_ReturnValue;         // 0x0159(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric) == 0x000008, "Wrong alignment on GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric");
static_assert(sizeof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric) == 0x000160, "Wrong size on GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, MyTarget) == 0x000000, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::MyTarget' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, Parameters) == 0x000008, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::Parameters' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, ParticleComponents) == 0x0000C0, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::ParticleComponents' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, AudioComponents) == 0x0000D0, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::AudioComponents' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, BurstCameraShakeInstance) == 0x0000E0, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::BurstCameraShakeInstance' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, BurstDecalInstance) == 0x0000E8, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::BurstDecalInstance' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_GetPlayerPawn_ReturnValue) == 0x0000F0, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_GetPlayerPawn_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_Array_Get_Item) == 0x0000F8, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_AsFort_Player_Pawn) == 0x000100, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_AsFort_Player_Pawn' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_bSuccess) == 0x000108, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_bSuccess' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_AsNiagara_Particle_System) == 0x000110, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_AsNiagara_Particle_System' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_bSuccess_1) == 0x000118, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_bSuccess_1' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_AsFort_Player_Pawn_1) == 0x000120, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_AsFort_Player_Pawn_1' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_bSuccess_2) == 0x000128, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_bSuccess_2' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_GetSocketLocation_ReturnValue) == 0x00012C, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_GetSocketLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_K2_GetComponentLocation_ReturnValue) == 0x000138, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_K2_GetComponentLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_SpawnSystemAtLocation_ReturnValue) == 0x000148, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_SpawnSystemAtLocation_ReturnValue' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_AsFort_Player_Pawn_2) == 0x000150, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_AsFort_Player_Pawn_2' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, K2Node_DynamicCast_bSuccess_3) == 0x000158, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::K2Node_DynamicCast_bSuccess_3' has a wrong offset!");
static_assert(offsetof(GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric, CallFunc_K2_AttachToComponent_ReturnValue) == 0x000159, "Member 'GCN_Cosmos_Rifle_MeleeImpact_C_OnBurstGeneric::CallFunc_K2_AttachToComponent_ReturnValue' has a wrong offset!");

}

