#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GCN_Athena_Health_HealUsed

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GCN_Athena_Health_HealUsed.GCN_Athena_Health_HealUsed_C
// 0x0000 (0x01C0 - 0x01C0)
class UGCN_Athena_Health_HealUsed_C final : public UFortGameplayCueNotify_Burst
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GCN_Athena_Health_HealUsed_C">();
	}
	static class UGCN_Athena_Health_HealUsed_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGCN_Athena_Health_HealUsed_C>();
	}
};

}

