#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GE_SpookyMist_BlockingApply

#include "Basic.hpp"

#include "GameplayAbilities_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GE_SpookyMist_BlockingApply.GE_SpookyMist_BlockingApply_C
// 0x0000 (0x0800 - 0x0800)
class UGE_SpookyMist_BlockingApply_C final : public UGameplayEffect
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"GE_SpookyMist_BlockingApply_C">();
	}
	static class UGE_SpookyMist_BlockingApply_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UGE_SpookyMist_BlockingApply_C>();
	}
};

}

