#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: HorizontalTabList

#include "Basic.hpp"

#include "SlateCore_structs.hpp"
#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"
#include "CommonInput_structs.hpp"
#include "UMG_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass HorizontalTabList.HorizontalTabList_C
// 0x0070 (0x0450 - 0x03E0)
class UHorizontalTabList_C final : public UFortTabListWidgetBase
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x03E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UImage*                                 ImageGamepadKeyPrompt;                             // 0x03E8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 ImageHorizRule;                                    // 0x03F0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    NextTabAction;                                     // 0x03F8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               NextTabActionWrapper;                              // 0x0400(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               Overlay_Container;                                 // 0x0408(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UCommonActionWidget*                    PreviousTabAction;                                 // 0x0410(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               PreviousTabActionWrapper;                          // 0x0418(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UHorizontalBox*                         TabButtonBox;                                      // 0x0420(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	struct FMargin                                TabButtonPadding;                                  // 0x0428(0x0010)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	class UClass*                                 ButtonStyle;                                       // 0x0438(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn, HasGetValueTypeHash)
	bool                                          UseButtonStyle;                                    // 0x0440(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          ShowGamePadInputPrompt;                            // 0x0441(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          ShowRail;                                          // 0x0442(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	uint8                                         Pad_443[0x1];                                      // 0x0443(0x0001)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         MinTabWidth;                                       // 0x0444(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          ForceTabLabelsCollapsed;                           // 0x0448(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)
	bool                                          ForceTabIconsCollapsed;                            // 0x0449(0x0001)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, ExposeOnSpawn)

public:
	void SetVerticalAlignment(EVerticalAlignment FillVertically);
	void UpdateGamepadKeyVisibility();
	class UCommonButton* Get_Tab_From_Id(class FName TabNameID);
	void Construct();
	void PreConstruct(bool IsDesignTime);
	void Previous_Visibility();
	void CustomEvent_0(class FName TabId);
	void HandleTabCreated(class FName TabNameID, class UCommonButton* TabButton);
	void HandleTabRemoved(class FName TabNameID, class UCommonButton* TabButton);
	void HandleOnInputMethodChanged(ECommonInputType bNewInputType);
	void ExecuteUbergraph_HorizontalTabList(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"HorizontalTabList_C">();
	}
	static class UHorizontalTabList_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UHorizontalTabList_C>();
	}
};
static_assert(alignof(UHorizontalTabList_C) == 0x000008, "Wrong alignment on UHorizontalTabList_C");
static_assert(sizeof(UHorizontalTabList_C) == 0x000450, "Wrong size on UHorizontalTabList_C");
static_assert(offsetof(UHorizontalTabList_C, UberGraphFrame) == 0x0003E0, "Member 'UHorizontalTabList_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ImageGamepadKeyPrompt) == 0x0003E8, "Member 'UHorizontalTabList_C::ImageGamepadKeyPrompt' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ImageHorizRule) == 0x0003F0, "Member 'UHorizontalTabList_C::ImageHorizRule' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, NextTabAction) == 0x0003F8, "Member 'UHorizontalTabList_C::NextTabAction' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, NextTabActionWrapper) == 0x000400, "Member 'UHorizontalTabList_C::NextTabActionWrapper' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, Overlay_Container) == 0x000408, "Member 'UHorizontalTabList_C::Overlay_Container' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, PreviousTabAction) == 0x000410, "Member 'UHorizontalTabList_C::PreviousTabAction' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, PreviousTabActionWrapper) == 0x000418, "Member 'UHorizontalTabList_C::PreviousTabActionWrapper' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, TabButtonBox) == 0x000420, "Member 'UHorizontalTabList_C::TabButtonBox' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, TabButtonPadding) == 0x000428, "Member 'UHorizontalTabList_C::TabButtonPadding' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ButtonStyle) == 0x000438, "Member 'UHorizontalTabList_C::ButtonStyle' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, UseButtonStyle) == 0x000440, "Member 'UHorizontalTabList_C::UseButtonStyle' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ShowGamePadInputPrompt) == 0x000441, "Member 'UHorizontalTabList_C::ShowGamePadInputPrompt' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ShowRail) == 0x000442, "Member 'UHorizontalTabList_C::ShowRail' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, MinTabWidth) == 0x000444, "Member 'UHorizontalTabList_C::MinTabWidth' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ForceTabLabelsCollapsed) == 0x000448, "Member 'UHorizontalTabList_C::ForceTabLabelsCollapsed' has a wrong offset!");
static_assert(offsetof(UHorizontalTabList_C, ForceTabIconsCollapsed) == 0x000449, "Member 'UHorizontalTabList_C::ForceTabIconsCollapsed' has a wrong offset!");

}

