#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Interop_AssetHelper

#include "Basic.hpp"


namespace SDK::Params
{

// Function Interop_AssetHelper.AssetHelper.loadAsset_Internal
// 0x0018 (0x0018 - 0x0000)
struct AssetHelper_loadAsset_Internal final
{
public:
	class FString                                 __verse_0x5D4EDCE6_pathToAsset;                    // 0x0000(0x0010)(Parm, ZeroConstructor, HasGetValueTypeHash)
	class UObject*                                RetVal;                                            // 0x0010(0x0008)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(AssetHelper_loadAsset_Internal) == 0x000008, "Wrong alignment on AssetHelper_loadAsset_Internal");
static_assert(sizeof(AssetHelper_loadAsset_Internal) == 0x000018, "Wrong size on AssetHelper_loadAsset_Internal");
static_assert(offsetof(AssetHelper_loadAsset_Internal, __verse_0x5D4EDCE6_pathToAsset) == 0x000000, "Member 'AssetHelper_loadAsset_Internal::__verse_0x5D4EDCE6_pathToAsset' has a wrong offset!");
static_assert(offsetof(AssetHelper_loadAsset_Internal, RetVal) == 0x000010, "Member 'AssetHelper_loadAsset_Internal::RetVal' has a wrong offset!");

}

