#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: InZoneTitleBar

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass InZoneTitleBar.InZoneTitleBar_C
// 0x0000 (0x0340 - 0x0340)
class UInZoneTitleBar_C final : public UInZoneTitleBarBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"InZoneTitleBar_C">();
	}
	static class UInZoneTitleBar_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UInZoneTitleBar_C>();
	}
};

}

