#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: IslandPortalInteractionInterface

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass IslandPortalInteractionInterface.IslandPortalInteractionInterface_C
// 0x0000 (0x0000 - 0x0000)
class IIslandPortalInteractionInterface_C final
{
public:
	void BroadcastIsBeingInteractedWith(bool IsInteracting);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"IslandPortalInteractionInterface_C">();
	}
	static class IIslandPortalInteractionInterface_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<IIslandPortalInteractionInterface_C>();
	}

	class UObject* AsUObject()
	{
		return reinterpret_cast<UObject*>(this);
	}
	const class UObject* AsUObject() const
	{
		return reinterpret_cast<const UObject*>(this);
	}
};

}

