#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LargeSidewaysPlayspace

#include "Basic.hpp"

#include "LargeSidewaysPlayspace_classes.hpp"
#include "LargeSidewaysPlayspace_parameters.hpp"


namespace SDK
{

// Function LargeSidewaysPlayspace.LargeSidewaysPlayspace_C.ExecuteUbergraph_LargeSidewaysPlayspace
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ALargeSidewaysPlayspace_C::ExecuteUbergraph_LargeSidewaysPlayspace(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LargeSidewaysPlayspace_C", "ExecuteUbergraph_LargeSidewaysPlayspace");

	Params::LargeSidewaysPlayspace_C_ExecuteUbergraph_LargeSidewaysPlayspace Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function LargeSidewaysPlayspace.LargeSidewaysPlayspace_C.NotifyPlayspaceUserAdded_Event_0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPlayspaceUser&            AddedUser                                              (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ALargeSidewaysPlayspace_C::NotifyPlayspaceUserAdded_Event_0(const struct FPlayspaceUser& AddedUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LargeSidewaysPlayspace_C", "NotifyPlayspaceUserAdded_Event_0");

	Params::LargeSidewaysPlayspace_C_NotifyPlayspaceUserAdded_Event_0 Parms{};

	Parms.AddedUser = std::move(AddedUser);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LargeSidewaysPlayspace.LargeSidewaysPlayspace_C.NotifyPlayspaceUserRemoved_Event_0
// (HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const struct FPlayspaceUser&            RemovedUser                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)

void ALargeSidewaysPlayspace_C::NotifyPlayspaceUserRemoved_Event_0(const struct FPlayspaceUser& RemovedUser)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LargeSidewaysPlayspace_C", "NotifyPlayspaceUserRemoved_Event_0");

	Params::LargeSidewaysPlayspace_C_NotifyPlayspaceUserRemoved_Event_0 Parms{};

	Parms.RemovedUser = std::move(RemovedUser);

	UObject::ProcessEvent(Func, &Parms);
}


// Function LargeSidewaysPlayspace.LargeSidewaysPlayspace_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ALargeSidewaysPlayspace_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("LargeSidewaysPlayspace_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}

}

