#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LF_1x1_Foundation

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass LF_1x1_Foundation.LF_1x1_Foundation_C
// 0x0000 (0x1030 - 0x1030)
class ALF_1x1_Foundation_C final : public ABuildingFoundation5x5
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"LF_1x1_Foundation_C">();
	}
	static class ALF_1x1_Foundation_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<ALF_1x1_Foundation_C>();
	}
};

}

