#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: LF_Athena_Grid_64x64

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function LF_Athena_Grid_64x64.LF_Athena_Grid_64x64_C.ReceiveEndPlay
// 0x0001 (0x0001 - 0x0000)
struct LF_Athena_Grid_64x64_C_ReceiveEndPlay final
{
public:
	EEndPlayReason                                EndPlayReason;                                     // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

// Function LF_Athena_Grid_64x64.LF_Athena_Grid_64x64_C.ExecuteUbergraph_LF_Athena_Grid_64x64
// 0x0008 (0x0008 - 0x0000)
struct LF_Athena_Grid_64x64_C_ExecuteUbergraph_LF_Athena_Grid_64x64 final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EEndPlayReason                                K2Node_Event_EndPlayReason;                        // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

