#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Math_Plane4

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass Math_Plane4.Plane4
// 0x0010 (0x0038 - 0x0028)
class UPlane4 final : public UObject
{
public:
	class UVector3*                               __verse_0x94528ACF_base;                           // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UVector3*                               __verse_0x3F33EAC9_normal;                         // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

public:
	static class UPlane4* Create(class UVector3* __verse_0xB04E112A_inBase, class UVector3* __verse_0x06073D83_inNormal);
	static class UPlane4* createZero();

	void _InitCDO();
	void _InitInstance();
	class UVector3* segmentIntersection(class UVector3* __verse_0x93ADD079_pointA, class UVector3* __verse_0x7D02656B_pointB);
	class FString ToString();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"Plane4">();
	}
	static class UPlane4* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlane4>();
	}
};
static_assert(alignof(UPlane4) == 0x000008, "Wrong alignment on UPlane4");
static_assert(sizeof(UPlane4) == 0x000038, "Wrong size on UPlane4");
static_assert(offsetof(UPlane4, __verse_0x94528ACF_base) == 0x000028, "Member 'UPlane4::__verse_0x94528ACF_base' has a wrong offset!");
static_assert(offsetof(UPlane4, __verse_0x3F33EAC9_normal) == 0x000030, "Member 'UPlane4::__verse_0x3F33EAC9_normal' has a wrong offset!");

}

