#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MissionGen_PhosphorusWipeout

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass MissionGen_PhosphorusWipeout.MissionGen_PhosphorusWipeout_C
// 0x0000 (0x06C8 - 0x06C8)
class UMissionGen_PhosphorusWipeout_C final : public UFortMissionGenerator
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"MissionGen_PhosphorusWipeout_C">();
	}
	static class UMissionGen_PhosphorusWipeout_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UMissionGen_PhosphorusWipeout_C>();
	}
};
static_assert(alignof(UMissionGen_PhosphorusWipeout_C) == 0x000008, "Wrong alignment on UMissionGen_PhosphorusWipeout_C");
static_assert(sizeof(UMissionGen_PhosphorusWipeout_C) == 0x0006C8, "Wrong size on UMissionGen_PhosphorusWipeout_C");

}

