#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayerSurveyWidget

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PlayerSurveyWidget.PlayerSurveyWidget_C
// 0x0000 (0x0528 - 0x0528)
class UPlayerSurveyWidget_C final : public UFortPlayerSurveyWidgetBase
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PlayerSurveyWidget_C">();
	}
	static class UPlayerSurveyWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerSurveyWidget_C>();
	}
};

}

