#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PlayJiggleTiresAnimation_Interface

#include "Basic.hpp"


namespace SDK::Params
{

// Function PlayJiggleTiresAnimation_Interface.PlayJiggleTiresAnimation_Interface_C.PlayJiggleTiresAnimation
// 0x0008 (0x0008 - 0x0000)
struct PlayJiggleTiresAnimation_Interface_C_PlayJiggleTiresAnimation final
{
public:
	float                                         StartFrame;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	float                                         EndFrame;                                          // 0x0004(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

