#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PopupCenterMessageModalPanel

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PopupCenterMessageModalPanel.PopupCenterMessageModalPanel_C
// 0x0040 (0x04E8 - 0x04A8)
class UPopupCenterMessageModalPanel_C final : public UFortPopUpCenterMessageModalPanel
{
public:
	class UCommonTextBlock*                       CenterMessageText;                                 // 0x04A8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UOverlay*                               MessageOverlay;                                    // 0x04B0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FText                                   WaitingForPlayersText;                             // 0x04B8(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)
	class FText                                   WaitingForOutpostOwnerText;                        // 0x04D0(0x0018)(Edit, BlueprintVisible, DisableEditOnInstance)

public:
	void UpdateState(ECenterPopupMessageStateEnum NewState);
	void LeaveZone();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PopupCenterMessageModalPanel_C">();
	}
	static class UPopupCenterMessageModalPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPopupCenterMessageModalPanel_C>();
	}
};

}

