#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ProgressModalWidget

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ProgressModalWidget.ProgressModalWidget_C
// 0x0010 (0x05A0 - 0x0590)
class UProgressModalWidget_C final : public UFortProgressModal
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0590(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class ULightbox_C*                            Lightbox;                                          // 0x0598(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void OnBeginOutro();
	void OnBeginIntro();
	struct FEventReply OnAnalogValueChanged(const struct FGeometry& MyGeometry, const struct FAnalogInputEvent& InAnalogInputEvent);
	void HandleOutroEnded();
	void HandleIntroEnded();
	void ExecuteUbergraph_ProgressModalWidget(int32 EntryPoint);
	void Destruct();
	void Construct();

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ProgressModalWidget_C">();
	}
	static class UProgressModalWidget_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UProgressModalWidget_C>();
	}
};

}

