#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: PunchCardNotification

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass PunchCardNotification.PunchCardNotification_C
// 0x0020 (0x02D8 - 0x02B8)
class UPunchCardNotification_C final : public UFortNotificationEntry_PunchCard
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02B8(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Outro;                                             // 0x02C0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x02C8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UVerticalBox*                           VerticalBox_0;                                     // 0x02D0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void Construct();
	void Destruct();
	void ExecuteUbergraph_PunchCardNotification(int32 EntryPoint);
	void play_intro();
	void StartNotificationIntro();
	void StartNotificationOutro();
	void WidgetAnimationEvt_Outro_K2Node_WidgetAnimationEvent_0();
	void XpSubNotification_Event_0(class UXpSubNotification_C* XpSubNotification_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"PunchCardNotification_C">();
	}
	static class UPunchCardNotification_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPunchCardNotification_C>();
	}
};

}

