#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SettingsPanel

#include "Basic.hpp"

#include "FortniteUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass SettingsPanel.SettingsPanel_C
// 0x0008 (0x06C0 - 0x06B8)
class USettingsPanel_C final : public UFortSettingsPanel
{
public:
	class USafeZone*                              SafeZone_0;                                        // 0x06B8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SettingsPanel_C">();
	}
	static class USettingsPanel_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USettingsPanel_C>();
	}
};

}

