#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShadowProxyMeshComponent

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass ShadowProxyMeshComponent.ShadowProxyMeshComponent_C
// 0x0030 (0x0510 - 0x04E0)
class UShadowProxyMeshComponent_C final : public UStaticMeshComponent
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x04E0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	bool                                          parentDefault_CastShadow;                          // 0x04E8(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4E9[0x7];                                      // 0x04E9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 cvarString;                                        // 0x04F0(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, HasGetValueTypeHash)
	bool                                          isProxyActive;                                     // 0x0500(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          forceShadowDisabled;                               // 0x0501(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_502[0x6];                                      // 0x0502(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UMeshComponent*                         ParentComponent;                                   // 0x0508(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, IsPlainOldData, NoDestructor, UObjectWrapper, HasGetValueTypeHash)

public:
	void validateShadowSettings();
	void setProxyShadowForceDisabled(bool forceShadowDisabled_0);
	void ReceiveBeginPlay();
	void handleOwnerDamaged();
	void handleCvarChanged(const class FString& CVarName);
	bool getProxyVisibility();
	void GetParentComponent(class UMeshComponent** AsMesh_Component);
	void ExecuteUbergraph_ShadowProxyMeshComponent(int32 EntryPoint);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShadowProxyMeshComponent_C">();
	}
	static class UShadowProxyMeshComponent_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShadowProxyMeshComponent_C>();
	}
};

}

