#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ShowdownEventTile

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "CommonUI_classes.hpp"
#include "FortniteUI_structs.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass ShowdownEventTile.ShowdownEventTile_C
// 0x00B0 (0x0C50 - 0x0BA0)
class UShowdownEventTile_C final : public UCommonButton
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0BA0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UWidgetAnimation*                       Focus_Violator;                                    // 0x0BA8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Hover;                                             // 0x0BB0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Focus;                                             // 0x0BB8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       TransitionSize;                                    // 0x0BC0(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UWidgetAnimation*                       Intro;                                             // 0x0BC8(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class UCommonBorder*                          CommonBorder_InputContainer;                       // 0x0BD0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Bg;                                          // 0x0BD8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Ended;                                       // 0x0BE0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Focus;                                       // 0x0BE8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Hover;                                       // 0x0BF0(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UImage*                                 Image_Tail;                                        // 0x0BF8(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UShowdownEventTile_RoundBreak_C*        ShowdownEventTile_RoundBreak;                      // 0x0C00(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UShowdownEventTileInfo_C*               ShowdownEventTileInfo;                             // 0x0C08(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class UShowdownEventTileViolator_C*           Violator;                                          // 0x0C10(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class FString                                 EventId;                                           // 0x0C18(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)
	bool                                          isEnded;                                           // 0x0C28(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	bool                                          isLive;                                            // 0x0C29(0x0001)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, IsPlainOldData, NoDestructor)
	uint8                                         Pad_C2A[0x6];                                      // 0x0C2A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	TMulticastInlineDelegate<void()>              OnWindowSelected;                                  // 0x0C30(0x0010)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, BlueprintAssignable, BlueprintCallable)
	class FString                                 TournamentId;                                      // 0x0C40(0x0010)(Edit, BlueprintVisible, ZeroConstructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_ShowdownEventTile(int32 EntryPoint);
	void EventMultiRoundStyle();
	void EventColorizeDispatch(const struct FFortTournamentDisplayInfo& DisplayInfo);
	void EventColorize(const struct FFortTournamentDisplayInfo& DisplayInfo);
	void EventSetState(EFortShowdownEventState EventState);
	void OnRemovedFromFocusPath(const struct FFocusEvent& InFocusEvent);
	void OnAddedToFocusPath(const struct FFocusEvent& InFocusEvent);
	void BP_OnDeselected();
	void BP_OnSelected();
	void BP_OnUnhovered();
	void BP_OnHovered();
	void EventResize(bool Out);
	void EventIntro(int32 Index_0);
	void BP_OnClicked();
	void Construct();
	void SetData(const class FString& TournamentInfo, const class FString& EventInfo);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"ShowdownEventTile_C">();
	}
	static class UShowdownEventTile_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UShowdownEventTile_C>();
	}
};
static_assert(alignof(UShowdownEventTile_C) == 0x000008, "Wrong alignment on UShowdownEventTile_C");
static_assert(sizeof(UShowdownEventTile_C) == 0x000C50, "Wrong size on UShowdownEventTile_C");
static_assert(offsetof(UShowdownEventTile_C, UberGraphFrame) == 0x000BA0, "Member 'UShowdownEventTile_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Focus_Violator) == 0x000BA8, "Member 'UShowdownEventTile_C::Focus_Violator' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Hover) == 0x000BB0, "Member 'UShowdownEventTile_C::Hover' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Focus) == 0x000BB8, "Member 'UShowdownEventTile_C::Focus' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, TransitionSize) == 0x000BC0, "Member 'UShowdownEventTile_C::TransitionSize' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Intro) == 0x000BC8, "Member 'UShowdownEventTile_C::Intro' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, CommonBorder_InputContainer) == 0x000BD0, "Member 'UShowdownEventTile_C::CommonBorder_InputContainer' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Image_Bg) == 0x000BD8, "Member 'UShowdownEventTile_C::Image_Bg' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Image_Ended) == 0x000BE0, "Member 'UShowdownEventTile_C::Image_Ended' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Image_Focus) == 0x000BE8, "Member 'UShowdownEventTile_C::Image_Focus' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Image_Hover) == 0x000BF0, "Member 'UShowdownEventTile_C::Image_Hover' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Image_Tail) == 0x000BF8, "Member 'UShowdownEventTile_C::Image_Tail' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, ShowdownEventTile_RoundBreak) == 0x000C00, "Member 'UShowdownEventTile_C::ShowdownEventTile_RoundBreak' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, ShowdownEventTileInfo) == 0x000C08, "Member 'UShowdownEventTile_C::ShowdownEventTileInfo' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, Violator) == 0x000C10, "Member 'UShowdownEventTile_C::Violator' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, EventId) == 0x000C18, "Member 'UShowdownEventTile_C::EventId' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, isEnded) == 0x000C28, "Member 'UShowdownEventTile_C::isEnded' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, isLive) == 0x000C29, "Member 'UShowdownEventTile_C::isLive' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, OnWindowSelected) == 0x000C30, "Member 'UShowdownEventTile_C::OnWindowSelected' has a wrong offset!");
static_assert(offsetof(UShowdownEventTile_C, TournamentId) == 0x000C40, "Member 'UShowdownEventTile_C::TournamentId' has a wrong offset!");

}

