#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SK_ChillBronco_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Engine_classes.hpp"
#include "AnimGraphRuntime_structs.hpp"


namespace SDK
{

// AnimBlueprintGeneratedClass SK_ChillBronco_AnimBP.SK_ChillBronco_AnimBP_C
// 0x0CC0 (0x0F80 - 0x02C0)
class USK_ChillBronco_AnimBP_C final : public UAnimInstance
{
public:
	uint8                                         Pad_2B8[0x8];                                      // 0x02B8(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	struct FAnimInstanceSubsystemData             AnimBlueprintClassSubsystem_PropertyAccess;        // 0x02C8(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2C9[0x7];                                      // 0x02C9(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_ConvertComponentToLocalSpace AnimGraphNode_ComponentToLocalSpace;               // 0x02D0(0x0020)()
	struct FAnimNode_ConvertLocalToComponentSpace AnimGraphNode_LocalToComponentSpace;               // 0x02F0(0x0020)()
	struct FAnimNode_AnimDynamics                 AnimGraphNode_AnimDynamics;                        // 0x0310(0x0440)()
	struct FAnimNode_LinkedInputPose              AnimGraphNode_SubInput;                            // 0x0750(0x0088)()
	struct FAnimNode_Root                         AnimGraphNode_Root;                                // 0x07D8(0x0030)()
	uint8                                         Pad_808[0x8];                                      // 0x0808(0x0008)(Fixing Size After Last Property [ Dumper-7 ])
	struct FAnimNode_RigidBody                    AnimGraphNode_RigidBody;                           // 0x0810(0x0660)()
	struct FAnimNode_ModifyBone                   AnimGraphNode_ModifyBone;                          // 0x0E70(0x0108)()

public:
	void ExecuteUbergraph_SK_ChillBronco_AnimBP(int32 EntryPoint);
	void AnimGraph(const struct FPoseLink& InPose, struct FPoseLink* AnimGraph_0);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"SK_ChillBronco_AnimBP_C">();
	}
	static class USK_ChillBronco_AnimBP_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<USK_ChillBronco_AnimBP_C>();
	}
};
static_assert(alignof(USK_ChillBronco_AnimBP_C) == 0x000010, "Wrong alignment on USK_ChillBronco_AnimBP_C");
static_assert(sizeof(USK_ChillBronco_AnimBP_C) == 0x000F80, "Wrong size on USK_ChillBronco_AnimBP_C");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, UberGraphFrame) == 0x0002C0, "Member 'USK_ChillBronco_AnimBP_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimBlueprintClassSubsystem_PropertyAccess) == 0x0002C8, "Member 'USK_ChillBronco_AnimBP_C::AnimBlueprintClassSubsystem_PropertyAccess' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_ComponentToLocalSpace) == 0x0002D0, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_ComponentToLocalSpace' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_LocalToComponentSpace) == 0x0002F0, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_LocalToComponentSpace' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_AnimDynamics) == 0x000310, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_AnimDynamics' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_SubInput) == 0x000750, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_SubInput' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_Root) == 0x0007D8, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_Root' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_RigidBody) == 0x000810, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_RigidBody' has a wrong offset!");
static_assert(offsetof(USK_ChillBronco_AnimBP_C, AnimGraphNode_ModifyBone) == 0x000E70, "Member 'USK_ChillBronco_AnimBP_C::AnimGraphNode_ModifyBone' has a wrong offset!");

}

