#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SolarisInterop

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class SolarisInterop.VerseAsset
// 0x0008 (0x0030 - 0x0028)
class UVerseAsset : public UObject
{
public:
	class UClass*                                 AssetClass;                                        // 0x0028(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, Protected, HasGetValueTypeHash, NativeAccessSpecifierProtected)

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VerseAsset">();
	}
	static class UVerseAsset* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVerseAsset>();
	}
};
static_assert(alignof(UVerseAsset) == 0x000008, "Wrong alignment on UVerseAsset");
static_assert(sizeof(UVerseAsset) == 0x000030, "Wrong size on UVerseAsset");
static_assert(offsetof(UVerseAsset, AssetClass) == 0x000028, "Member 'UVerseAsset::AssetClass' has a wrong offset!");

// Class SolarisInterop.CoroutineContextPlaceholder
// 0x00F0 (0x0118 - 0x0028)
class UCoroutineContextPlaceholder final : public UObject
{
public:
	uint8                                         Pad_28[0xF0];                                      // 0x0028(0x00F0)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"CoroutineContextPlaceholder">();
	}
	static class UCoroutineContextPlaceholder* GetDefaultObj()
	{
		return GetDefaultObjImpl<UCoroutineContextPlaceholder>();
	}
};
static_assert(alignof(UCoroutineContextPlaceholder) == 0x000008, "Wrong alignment on UCoroutineContextPlaceholder");
static_assert(sizeof(UCoroutineContextPlaceholder) == 0x000118, "Wrong size on UCoroutineContextPlaceholder");

}

