#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Struct_Athena_SidewaysEncounter_EnvActors

#include "Basic.hpp"

#include "GameplayAbilities_structs.hpp"


namespace SDK
{

// UserDefinedStruct Struct_Athena_SidewaysEncounter_EnvActors.Struct_Athena_SidewaysEncounter_EnvActors
// 0x0140 (0x0140 - 0x0000)
struct FStruct_Athena_SidewaysEncounter_EnvActors final
{
public:
	class UClass*                                 Chest_34_122DA6DE47AB0AEE5BB057877B9ADC45;         // 0x0000(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         Chests_MinAmount_22_D6EF526C45D747A71D2E678718B924DF; // 0x0008(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         Chests_MaxAmount_23_348B992D449B29EB33888FB784CE4041; // 0x0030(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         ChanceForSuperChest_10_9FA7ABBB4D7F6E87780C01A7C0A49487; // 0x0058(0x0028)(Edit, BlueprintVisible)
	class UClass*                                 SuperChest_33_63C10A4946349F3D9F5E03B9B1CE7ABB;    // 0x0080(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class UClass*>                         Pillars_32_CC551FD049599D6FA20AC08077B5E2B8;       // 0x0088(0x0010)(Edit, BlueprintVisible)
	struct FScalableFloat                         Pillars_MinAmount_29_BD70636A4F868EC0A01EA289494C79E4; // 0x0098(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         Pillars_MaxAmount_30_343259ED47B13E9F8AF8CFAB693721AF; // 0x00C0(0x0028)(Edit, BlueprintVisible)
	class UClass*                                 ExplosivePods_36_59506DE44B8798490E51908F5EAE5065; // 0x00E8(0x0008)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FScalableFloat                         ExplosivePods_MinAmount_25_18247FEE4074C758C04C5BA5213AACB4; // 0x00F0(0x0028)(Edit, BlueprintVisible)
	struct FScalableFloat                         ExplosivePods_MaxAmount_26_11D3727745D52357569A49BC1ED30844; // 0x0118(0x0028)(Edit, BlueprintVisible)
};

}

