#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: SubgameSelectScreen

#include "Basic.hpp"

#include "FortniteUI_structs.hpp"
#include "CoreUObject_structs.hpp"
#include "FortniteGame_structs.hpp"


namespace SDK::Params
{

// Function SubgameSelectScreen.SubgameSelectScreen_C.ExecuteUbergraph_SubgameSelectScreen
// 0x0148 (0x0148 - 0x0000)
struct SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortDialogResult                             K2Node_CustomEvent_Result;                         // 0x0004(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_5[0x3];                                        // 0x0005(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   K2Node_CustomEvent_ResultName;                     // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(EFortDialogResult Result, class FName ResultName)> K2Node_CreateDelegate_OutputDelegate; // 0x0010(0x0010)(ZeroConstructor, NoDestructor)
	class FName                                   Temp_name_Variable;                                // 0x0020(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortDialogResult                             Temp_byte_Variable;                                // 0x0028(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          K2Node_SwitchEnum_CmpSuccess;                      // 0x0029(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_2A[0x6];                                       // 0x002A(0x0006)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortAsyncAction_ShowConfirmation_NUI*  CallFunc_ShowSimpleConfirmationDialog_NUI_ReturnValue; // 0x0030(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)> K2Node_CreateDelegate_OutputDelegate_1; // 0x0038(0x0010)(ZeroConstructor, NoDestructor)
	bool                                          CallFunc_IsValid_ReturnValue;                      // 0x0048(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_49[0x7];                                       // 0x0049(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_EventName_2;                    // 0x0050(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeUntilEnd_2;                 // 0x0060(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeSinceBegin_2;               // 0x0068(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_TimeSpanRatio_2;                // 0x0070(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_74[0x4];                                       // 0x0074(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_EventName_1;                    // 0x0078(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeUntilEnd_1;                 // 0x0088(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeSinceBegin_1;               // 0x0090(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_TimeSpanRatio_1;                // 0x0098(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)> K2Node_CreateDelegate_OutputDelegate_2; // 0x009C(0x0010)(ZeroConstructor, NoDestructor)
	uint8                                         Pad_AC[0x4];                                       // 0x00AC(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class FString                                 K2Node_CustomEvent_EventName;                      // 0x00B0(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeUntilEnd;                   // 0x00C0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              K2Node_CustomEvent_TimeSinceBegin;                 // 0x00C8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         K2Node_CustomEvent_TimeSpanRatio;                  // 0x00D0(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TDelegate<void(const class FString& EventName, const struct FTimespan& TimeUntilEnd, const struct FTimespan& TimeSinceBegin, float TimespanRatio)> K2Node_CreateDelegate_OutputDelegate_3; // 0x00D4(0x0010)(ZeroConstructor, NoDestructor)
	float                                         Temp_float_Variable;                               // 0x00E4(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              Temp_struct_Variable;                              // 0x00E8(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              Temp_struct_Variable_1;                            // 0x00F0(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	class FString                                 Temp_string_Variable;                              // 0x00F8(0x0010)(ZeroConstructor, HasGetValueTypeHash)
	class UFortAsyncAction_CalendarEventWatcher*  CallFunc_WatchCalendarEvent_ReturnValue;           // 0x0108(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_1;                    // 0x0110(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_111[0x7];                                      // 0x0111(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UCommonButton*                          K2Node_ComponentBoundEvent_Button;                 // 0x0118(0x0008)(ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	TArray<class AFort_Entry_Music_Controller_BP_C*> CallFunc_GetAllActorsOfClass_OutActors;         // 0x0120(0x0010)(ReferenceParm, HasGetValueTypeHash)
	class AFort_Entry_Music_Controller_BP_C*      CallFunc_Array_Get_Item;                           // 0x0130(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0138(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsValid_ReturnValue_2;                    // 0x0140(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen");
static_assert(sizeof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen) == 0x000148, "Wrong size on SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, EntryPoint) == 0x000000, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::EntryPoint' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_Result) == 0x000004, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_Result' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_ResultName) == 0x000008, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_ResultName' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CreateDelegate_OutputDelegate) == 0x000010, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CreateDelegate_OutputDelegate' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_name_Variable) == 0x000020, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_name_Variable' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_byte_Variable) == 0x000028, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_byte_Variable' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_SwitchEnum_CmpSuccess) == 0x000029, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_SwitchEnum_CmpSuccess' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_ShowSimpleConfirmationDialog_NUI_ReturnValue) == 0x000030, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_ShowSimpleConfirmationDialog_NUI_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CreateDelegate_OutputDelegate_1) == 0x000038, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CreateDelegate_OutputDelegate_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_IsValid_ReturnValue) == 0x000048, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_IsValid_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_EventName_2) == 0x000050, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_EventName_2' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeUntilEnd_2) == 0x000060, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeUntilEnd_2' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSinceBegin_2) == 0x000068, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSinceBegin_2' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSpanRatio_2) == 0x000070, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSpanRatio_2' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_EventName_1) == 0x000078, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_EventName_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeUntilEnd_1) == 0x000088, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeUntilEnd_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSinceBegin_1) == 0x000090, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSinceBegin_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSpanRatio_1) == 0x000098, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSpanRatio_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CreateDelegate_OutputDelegate_2) == 0x00009C, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CreateDelegate_OutputDelegate_2' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_EventName) == 0x0000B0, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_EventName' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeUntilEnd) == 0x0000C0, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeUntilEnd' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSinceBegin) == 0x0000C8, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSinceBegin' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CustomEvent_TimeSpanRatio) == 0x0000D0, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CustomEvent_TimeSpanRatio' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_CreateDelegate_OutputDelegate_3) == 0x0000D4, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_CreateDelegate_OutputDelegate_3' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_float_Variable) == 0x0000E4, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_float_Variable' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_struct_Variable) == 0x0000E8, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_struct_Variable' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_struct_Variable_1) == 0x0000F0, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_struct_Variable_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, Temp_string_Variable) == 0x0000F8, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::Temp_string_Variable' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_WatchCalendarEvent_ReturnValue) == 0x000108, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_WatchCalendarEvent_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_IsValid_ReturnValue_1) == 0x000110, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_IsValid_ReturnValue_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, K2Node_ComponentBoundEvent_Button) == 0x000118, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::K2Node_ComponentBoundEvent_Button' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_GetAllActorsOfClass_OutActors) == 0x000120, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_GetAllActorsOfClass_OutActors' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_Array_Get_Item) == 0x000130, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_GetContext_ReturnValue) == 0x000138, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen, CallFunc_IsValid_ReturnValue_2) == 0x000140, "Member 'SubgameSelectScreen_C_ExecuteUbergraph_SubgameSelectScreen::CallFunc_IsValid_ReturnValue_2' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature
// 0x0008 (0x0008 - 0x0000)
struct SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature final
{
public:
	class UCommonButton*                          Button;                                            // 0x0000(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature");
static_assert(sizeof(SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature) == 0x000008, "Wrong size on SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature");
static_assert(offsetof(SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature, Button) == 0x000000, "Member 'SubgameSelectScreen_C_BndEvt__ButtonExit_K2Node_ComponentBoundEvent_193_CommonButtonClicked__DelegateSignature::Button' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.OnEventActive_57187EC14A536D0960088EB25BDF39E5
// 0x0028 (0x0028 - 0x0000)
struct SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5 final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              TimeUntilEnd;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              TimeSinceBegin;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         TimespanRatio;                                     // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5");
static_assert(sizeof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5) == 0x000028, "Wrong size on SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5");
static_assert(offsetof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5, EventName) == 0x000000, "Member 'SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5::EventName' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5, TimeUntilEnd) == 0x000010, "Member 'SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5::TimeUntilEnd' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5, TimeSinceBegin) == 0x000018, "Member 'SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5::TimeSinceBegin' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5, TimespanRatio) == 0x000020, "Member 'SubgameSelectScreen_C_OnEventActive_57187EC14A536D0960088EB25BDF39E5::TimespanRatio' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.OnEventUpdated_57187EC14A536D0960088EB25BDF39E5
// 0x0028 (0x0028 - 0x0000)
struct SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5 final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              TimeUntilEnd;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              TimeSinceBegin;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         TimespanRatio;                                     // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5");
static_assert(sizeof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5) == 0x000028, "Wrong size on SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5");
static_assert(offsetof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5, EventName) == 0x000000, "Member 'SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5::EventName' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5, TimeUntilEnd) == 0x000010, "Member 'SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5::TimeUntilEnd' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5, TimeSinceBegin) == 0x000018, "Member 'SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5::TimeSinceBegin' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5, TimespanRatio) == 0x000020, "Member 'SubgameSelectScreen_C_OnEventUpdated_57187EC14A536D0960088EB25BDF39E5::TimespanRatio' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.OnEventEnded_57187EC14A536D0960088EB25BDF39E5
// 0x0028 (0x0028 - 0x0000)
struct SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5 final
{
public:
	class FString                                 EventName;                                         // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)
	struct FTimespan                              TimeUntilEnd;                                      // 0x0010(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	struct FTimespan                              TimeSinceBegin;                                    // 0x0018(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
	float                                         TimespanRatio;                                     // 0x0020(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5");
static_assert(sizeof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5) == 0x000028, "Wrong size on SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5");
static_assert(offsetof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5, EventName) == 0x000000, "Member 'SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5::EventName' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5, TimeUntilEnd) == 0x000010, "Member 'SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5::TimeUntilEnd' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5, TimeSinceBegin) == 0x000018, "Member 'SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5::TimeSinceBegin' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5, TimespanRatio) == 0x000020, "Member 'SubgameSelectScreen_C_OnEventEnded_57187EC14A536D0960088EB25BDF39E5::TimespanRatio' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.DialogResult_FE9F49084346A08B6F02BA99FB50F5CD
// 0x000C (0x000C - 0x0000)
struct SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD final
{
public:
	EFortDialogResult                             Result;                                            // 0x0000(0x0001)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_1[0x3];                                        // 0x0001(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	class FName                                   ResultName;                                        // 0x0004(0x0008)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD) == 0x000004, "Wrong alignment on SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD");
static_assert(sizeof(SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD) == 0x00000C, "Wrong size on SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD");
static_assert(offsetof(SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD, Result) == 0x000000, "Member 'SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD::Result' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD, ResultName) == 0x000004, "Member 'SubgameSelectScreen_C_DialogResult_FE9F49084346A08B6F02BA99FB50F5CD::ResultName' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.InitializeTextureCycle
// 0x0018 (0x0018 - 0x0000)
struct SubgameSelectScreen_C_InitializeTextureCycle final
{
public:
	class UTexture*                               CallFunc_Array_Get_Item;                           // 0x0000(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_LastIndex_ReturnValue;              // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture*                               CallFunc_Array_Get_Item_1;                         // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_InitializeTextureCycle) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_InitializeTextureCycle");
static_assert(sizeof(SubgameSelectScreen_C_InitializeTextureCycle) == 0x000018, "Wrong size on SubgameSelectScreen_C_InitializeTextureCycle");
static_assert(offsetof(SubgameSelectScreen_C_InitializeTextureCycle, CallFunc_Array_Get_Item) == 0x000000, "Member 'SubgameSelectScreen_C_InitializeTextureCycle::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_InitializeTextureCycle, CallFunc_Array_LastIndex_ReturnValue) == 0x000008, "Member 'SubgameSelectScreen_C_InitializeTextureCycle::CallFunc_Array_LastIndex_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_InitializeTextureCycle, CallFunc_Array_Get_Item_1) == 0x000010, "Member 'SubgameSelectScreen_C_InitializeTextureCycle::CallFunc_Array_Get_Item_1' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.AdvanceTextureCycle
// 0x0028 (0x0028 - 0x0000)
struct SubgameSelectScreen_C_AdvanceTextureCycle final
{
public:
	int32                                         NextTextureIndex;                                  // 0x0000(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CurrentTextureIndex;                               // 0x0004(0x0004)(Edit, BlueprintVisible, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         CallFunc_Array_Length_ReturnValue;                 // 0x0008(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_C[0x4];                                        // 0x000C(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UTexture*                               CallFunc_Array_Get_Item;                           // 0x0010(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	class UTexture*                               CallFunc_Array_Get_Item_1;                         // 0x0018(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_GreaterEqual_IntInt_ReturnValue;          // 0x0020(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_21[0x3];                                       // 0x0021(0x0003)(Fixing Size After Last Property [ Dumper-7 ])
	int32                                         CallFunc_Add_IntInt_ReturnValue;                   // 0x0024(0x0004)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(SubgameSelectScreen_C_AdvanceTextureCycle) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_AdvanceTextureCycle");
static_assert(sizeof(SubgameSelectScreen_C_AdvanceTextureCycle) == 0x000028, "Wrong size on SubgameSelectScreen_C_AdvanceTextureCycle");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, NextTextureIndex) == 0x000000, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::NextTextureIndex' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CurrentTextureIndex) == 0x000004, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CurrentTextureIndex' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CallFunc_Array_Length_ReturnValue) == 0x000008, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CallFunc_Array_Length_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CallFunc_Array_Get_Item) == 0x000010, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CallFunc_Array_Get_Item' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CallFunc_Array_Get_Item_1) == 0x000018, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CallFunc_Array_Get_Item_1' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CallFunc_GreaterEqual_IntInt_ReturnValue) == 0x000020, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CallFunc_GreaterEqual_IntInt_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_AdvanceTextureCycle, CallFunc_Add_IntInt_ReturnValue) == 0x000024, "Member 'SubgameSelectScreen_C_AdvanceTextureCycle::CallFunc_Add_IntInt_ReturnValue' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.IsBusyMatchmaking
// 0x0018 (0x0018 - 0x0000)
struct SubgameSelectScreen_C_IsBusyMatchmaking final
{
public:
	bool                                          ReturnValue;                                       // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortMatchmakingContext*                CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_IsMatchmakingLocal_ReturnValue;           // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SubgameSelectScreen_C_IsBusyMatchmaking) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_IsBusyMatchmaking");
static_assert(sizeof(SubgameSelectScreen_C_IsBusyMatchmaking) == 0x000018, "Wrong size on SubgameSelectScreen_C_IsBusyMatchmaking");
static_assert(offsetof(SubgameSelectScreen_C_IsBusyMatchmaking, ReturnValue) == 0x000000, "Member 'SubgameSelectScreen_C_IsBusyMatchmaking::ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsBusyMatchmaking, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'SubgameSelectScreen_C_IsBusyMatchmaking::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsBusyMatchmaking, CallFunc_IsMatchmakingLocal_ReturnValue) == 0x000010, "Member 'SubgameSelectScreen_C_IsBusyMatchmaking::CallFunc_IsMatchmakingLocal_ReturnValue' has a wrong offset!");

// Function SubgameSelectScreen.SubgameSelectScreen_C.IsMinorShutdownWarningEnabled
// 0x0018 (0x0018 - 0x0000)
struct SubgameSelectScreen_C_IsMinorShutdownWarningEnabled final
{
public:
	bool                                          Enabled;                                           // 0x0000(0x0001)(Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor)
	uint8                                         Pad_1[0x7];                                        // 0x0001(0x0007)(Fixing Size After Last Property [ Dumper-7 ])
	class UFortGlobalUIContext*                   CallFunc_GetContext_ReturnValue;                   // 0x0008(0x0008)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortUIFeatureState                           CallFunc_GetFeatureState_OutFeatureState;          // 0x0010(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	EFortUIFeatureStateReason                     CallFunc_GetFeatureState_OutReason;                // 0x0011(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	bool                                          CallFunc_EqualEqual_ByteByte_ReturnValue;          // 0x0012(0x0001)(ZeroConstructor, IsPlainOldData, NoDestructor)
};
static_assert(alignof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled) == 0x000008, "Wrong alignment on SubgameSelectScreen_C_IsMinorShutdownWarningEnabled");
static_assert(sizeof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled) == 0x000018, "Wrong size on SubgameSelectScreen_C_IsMinorShutdownWarningEnabled");
static_assert(offsetof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled, Enabled) == 0x000000, "Member 'SubgameSelectScreen_C_IsMinorShutdownWarningEnabled::Enabled' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled, CallFunc_GetContext_ReturnValue) == 0x000008, "Member 'SubgameSelectScreen_C_IsMinorShutdownWarningEnabled::CallFunc_GetContext_ReturnValue' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled, CallFunc_GetFeatureState_OutFeatureState) == 0x000010, "Member 'SubgameSelectScreen_C_IsMinorShutdownWarningEnabled::CallFunc_GetFeatureState_OutFeatureState' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled, CallFunc_GetFeatureState_OutReason) == 0x000011, "Member 'SubgameSelectScreen_C_IsMinorShutdownWarningEnabled::CallFunc_GetFeatureState_OutReason' has a wrong offset!");
static_assert(offsetof(SubgameSelectScreen_C_IsMinorShutdownWarningEnabled, CallFunc_EqualEqual_ByteByte_ReturnValue) == 0x000012, "Member 'SubgameSelectScreen_C_IsMinorShutdownWarningEnabled::CallFunc_EqualEqual_ByteByte_ReturnValue' has a wrong offset!");

}

