#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Tent_Pickup_Gadget_AnimBP

#include "Basic.hpp"

#include "Engine_structs.hpp"


namespace SDK::Params
{

// Function Tent_Pickup_Gadget_AnimBP.Tent_Pickup_Gadget_AnimBP_C.AnimGraph
// 0x0020 (0x0020 - 0x0000)
struct Tent_Pickup_Gadget_AnimBP_C_AnimGraph final
{
public:
	struct FPoseLink                              InPose;                                            // 0x0000(0x0010)(BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
	struct FPoseLink                              AnimGraph_0;                                       // 0x0010(0x0010)(Parm, OutParm, NoDestructor)
};

// Function Tent_Pickup_Gadget_AnimBP.Tent_Pickup_Gadget_AnimBP_C.ExecuteUbergraph_Tent_Pickup_Gadget_AnimBP
// 0x0004 (0x0004 - 0x0000)
struct Tent_Pickup_Gadget_AnimBP_C_ExecuteUbergraph_Tent_Pickup_Gadget_AnimBP final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};

}

