#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: TextStyle_ScorePlacementBronze

#include "Basic.hpp"

#include "TextStyle_ScorePlacementGold_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass TextStyle-ScorePlacementBronze.TextStyle-ScorePlacementBronze_C
// 0x0000 (0x0180 - 0x0180)
class UTextStyle_ScorePlacementBronze_C final : public UTextStyle_ScorePlacementGold_C
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"TextStyle-ScorePlacementBronze_C">();
	}
	static class UTextStyle_ScorePlacementBronze_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UTextStyle_ScorePlacementBronze_C>();
	}
};

}

