#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: Vendetta_Tank_Cosmetics

#include "Basic.hpp"

#include "FortniteGame_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass Vendetta_Tank_Cosmetics.Vendetta_Tank_Cosmetics_C
// 0x0000 (0x0130 - 0x0130)
class UVendetta_Tank_Cosmetics_C final : public UFortAthenaAISpawnerDataComponent_CosmeticLoadout
{
public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"Vendetta_Tank_Cosmetics_C">();
	}
	static class UVendetta_Tank_Cosmetics_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UVendetta_Tank_Cosmetics_C>();
	}
};
static_assert(alignof(UVendetta_Tank_Cosmetics_C) == 0x000008, "Wrong alignment on UVendetta_Tank_Cosmetics_C");
static_assert(sizeof(UVendetta_Tank_Cosmetics_C) == 0x000130, "Wrong size on UVendetta_Tank_Cosmetics_C");

}

