#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_Player_PlayerAttribute

#include "Basic.hpp"


namespace SDK
{

// SolarisGeneratedEnum VerseFortnite_Player_PlayerAttribute.PlayerAttribute
// NumValues: 0x0006
enum class EPlayerAttribute : uint8
{
	CurrentHealth                            = 0,
	CurrentShield                            = 1,
	InitialHealth                            = 2,
	InitialShield                            = 3,
	Damage                                   = 4,
	ShieldDamage                             = 5,
};

}

