#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_Datastore_DatastoreComponent

#include "Basic.hpp"

#include "VerseFortnite_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass VerseFortnite_Datastore_DatastoreComponent.DatastoreComponent
// 0x0000 (0x0220 - 0x0220)
class UDatastoreComponent final : public UDatastoreComponentBase
{
public:
	static void clearAllDatastoreValues(class UPlayerComponent* __verse_0x9F1D658F_player);
	static void setDatastoreValue(class UPlayerComponent* __verse_0x9F1D658F_player, const class FString& __verse_0xA04F29AC_key, const class FString& __verse_0x3AF80D16_value);

	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"DatastoreComponent">();
	}
	static class UDatastoreComponent* GetDefaultObj()
	{
		return GetDefaultObjImpl<UDatastoreComponent>();
	}
};
static_assert(alignof(UDatastoreComponent) == 0x000008, "Wrong alignment on UDatastoreComponent");
static_assert(sizeof(UDatastoreComponent) == 0x000220, "Wrong size on UDatastoreComponent");

}

