#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_Player_PlayerAttributes

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"
#include "VerseFortnite_Player_PlayerAttribute_structs.hpp"
#include "VerseFortnite_Player_PlayerAttributeOperation_structs.hpp"


namespace SDK
{

// SolarisGeneratedClass VerseFortnite_Player_PlayerAttributes.PlayerAttributes
// 0x0000 (0x0028 - 0x0028)
class UPlayerAttributes final : public UObject
{
public:
	static void addToNumericAttribute(class UPlayerComponent* __verse_0x9F1D658F_player, EPlayerAttribute __verse_0x8304B4A7_attributeID, float __verse_0x63C4C549_amount);
	static float getNumericAttributeValue(class UPlayerComponent* __verse_0x9F1D658F_player, EPlayerAttribute __verse_0x8304B4A7_attributeID);
	static void modifyNumericAttribute(class UPlayerComponent* __verse_0x9F1D658F_player, EPlayerAttribute __verse_0x8304B4A7_attributeID, EPlayerAttributeOperation __verse_0xE2CDD607_op, float __verse_0x63C4C549_amount);

	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"PlayerAttributes">();
	}
	static class UPlayerAttributes* GetDefaultObj()
	{
		return GetDefaultObjImpl<UPlayerAttributes>();
	}
};
static_assert(alignof(UPlayerAttributes) == 0x000008, "Wrong alignment on UPlayerAttributes");
static_assert(sizeof(UPlayerAttributes) == 0x000028, "Wrong size on UPlayerAttributes");

}

