#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_Item_ItemType

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// SolarisGeneratedClass VerseFortnite_Item_ItemType.ItemType
// 0x0008 (0x0030 - 0x0028)
class UItemType final : public UObject
{
public:
	uint8                                         Pad_28[0x8];                                       // 0x0028(0x0008)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void _InitCDO();
	void _InitInstance();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"ItemType">();
	}
	static class UItemType* GetDefaultObj()
	{
		return GetDefaultObjImpl<UItemType>();
	}
};
static_assert(alignof(UItemType) == 0x000008, "Wrong alignment on UItemType");
static_assert(sizeof(UItemType) == 0x000030, "Wrong size on UItemType");

}

