#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseSimulationMetadata

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// VerseClass VerseSimulationMetadata.Simulation
// 0x0000 (0x0028 - 0x0028)
class VerseSimulationMetadata::USimulation final : public UObject
{
public:
	void _InitCDO();

public:
	static class UClass* StaticClass()
	{
		return StaticClassImpl<"VerseClass VerseSimulationMetadata.Simulation", true>();
	}
	static class VerseSimulationMetadata::USimulation* GetDefaultObj()
	{
		return GetDefaultObjImpl<VerseSimulationMetadata::USimulation>();
	}
};
static_assert(alignof(VerseSimulationMetadata::USimulation) == 0x000008, "Wrong alignment on VerseSimulationMetadata::USimulation");
static_assert(sizeof(VerseSimulationMetadata::USimulation) == 0x000028, "Wrong size on VerseSimulationMetadata::USimulation");

}

