#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: VerseFortnite_MatchStats

#include "Basic.hpp"


namespace SDK::Params
{

// Function VerseFortnite_MatchStats.MatchStats.getMatchStat
// 0x0008 (0x0008 - 0x0000)
struct MatchStats_getMatchStat final
{
public:
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RetVal;                                            // 0x0004(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_getMatchStat) == 0x000004, "Wrong alignment on MatchStats_getMatchStat");
static_assert(sizeof(MatchStats_getMatchStat) == 0x000008, "Wrong size on MatchStats_getMatchStat");
static_assert(offsetof(MatchStats_getMatchStat, __verse_0x8C4546BB_statIndex) == 0x000000, "Member 'MatchStats_getMatchStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_getMatchStat, RetVal) == 0x000004, "Member 'MatchStats_getMatchStat::RetVal' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.getPlayerStat
// 0x0010 (0x0010 - 0x0000)
struct MatchStats_getPlayerStat final
{
public:
	class UPlayerComponent*                       __verse_0x9F1D658F_player;                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RetVal;                                            // 0x000C(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_getPlayerStat) == 0x000008, "Wrong alignment on MatchStats_getPlayerStat");
static_assert(sizeof(MatchStats_getPlayerStat) == 0x000010, "Wrong size on MatchStats_getPlayerStat");
static_assert(offsetof(MatchStats_getPlayerStat, __verse_0x9F1D658F_player) == 0x000000, "Member 'MatchStats_getPlayerStat::__verse_0x9F1D658F_player' has a wrong offset!");
static_assert(offsetof(MatchStats_getPlayerStat, __verse_0x8C4546BB_statIndex) == 0x000008, "Member 'MatchStats_getPlayerStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_getPlayerStat, RetVal) == 0x00000C, "Member 'MatchStats_getPlayerStat::RetVal' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.getTeamStat
// 0x000C (0x000C - 0x0000)
struct MatchStats_getTeamStat final
{
public:
	int32                                         __verse_0x28201082_team;                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         RetVal;                                            // 0x0008(0x0004)(Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_getTeamStat) == 0x000004, "Wrong alignment on MatchStats_getTeamStat");
static_assert(sizeof(MatchStats_getTeamStat) == 0x00000C, "Wrong size on MatchStats_getTeamStat");
static_assert(offsetof(MatchStats_getTeamStat, __verse_0x28201082_team) == 0x000000, "Member 'MatchStats_getTeamStat::__verse_0x28201082_team' has a wrong offset!");
static_assert(offsetof(MatchStats_getTeamStat, __verse_0x8C4546BB_statIndex) == 0x000004, "Member 'MatchStats_getTeamStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_getTeamStat, RetVal) == 0x000008, "Member 'MatchStats_getTeamStat::RetVal' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.incrementMatchStat
// 0x000C (0x000C - 0x0000)
struct MatchStats_incrementMatchStat final
{
public:
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8461104C_increase;                       // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x0008(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor))
};
static_assert(alignof(MatchStats_incrementMatchStat) == 0x000004, "Wrong alignment on MatchStats_incrementMatchStat");
static_assert(sizeof(MatchStats_incrementMatchStat) == 0x00000C, "Wrong size on MatchStats_incrementMatchStat");
static_assert(offsetof(MatchStats_incrementMatchStat, __verse_0x8C4546BB_statIndex) == 0x000000, "Member 'MatchStats_incrementMatchStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_incrementMatchStat, __verse_0x8461104C_increase) == 0x000004, "Member 'MatchStats_incrementMatchStat::__verse_0x8461104C_increase' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.incrementPlayerStat
// 0x0018 (0x0018 - 0x0000)
struct MatchStats_incrementPlayerStat final
{
public:
	class UPlayerComponent*                       __verse_0x9F1D658F_player;                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8461104C_increase;                       // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x0010(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor))
};
static_assert(alignof(MatchStats_incrementPlayerStat) == 0x000008, "Wrong alignment on MatchStats_incrementPlayerStat");
static_assert(sizeof(MatchStats_incrementPlayerStat) == 0x000018, "Wrong size on MatchStats_incrementPlayerStat");
static_assert(offsetof(MatchStats_incrementPlayerStat, __verse_0x9F1D658F_player) == 0x000000, "Member 'MatchStats_incrementPlayerStat::__verse_0x9F1D658F_player' has a wrong offset!");
static_assert(offsetof(MatchStats_incrementPlayerStat, __verse_0x8C4546BB_statIndex) == 0x000008, "Member 'MatchStats_incrementPlayerStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_incrementPlayerStat, __verse_0x8461104C_increase) == 0x00000C, "Member 'MatchStats_incrementPlayerStat::__verse_0x8461104C_increase' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.incrementTeamStat
// 0x0010 (0x0010 - 0x0000)
struct MatchStats_incrementTeamStat final
{
public:
	int32                                         __verse_0x28201082_team;                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8461104C_increase;                       // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         RetVal : 1;                                        // 0x000C(0x0001)(BitIndex: 0x00, PropSize: 0x0001 (Parm, OutParm, ReturnParm, NoDestructor))
};
static_assert(alignof(MatchStats_incrementTeamStat) == 0x000004, "Wrong alignment on MatchStats_incrementTeamStat");
static_assert(sizeof(MatchStats_incrementTeamStat) == 0x000010, "Wrong size on MatchStats_incrementTeamStat");
static_assert(offsetof(MatchStats_incrementTeamStat, __verse_0x28201082_team) == 0x000000, "Member 'MatchStats_incrementTeamStat::__verse_0x28201082_team' has a wrong offset!");
static_assert(offsetof(MatchStats_incrementTeamStat, __verse_0x8C4546BB_statIndex) == 0x000004, "Member 'MatchStats_incrementTeamStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_incrementTeamStat, __verse_0x8461104C_increase) == 0x000008, "Member 'MatchStats_incrementTeamStat::__verse_0x8461104C_increase' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.setMatchStat
// 0x0008 (0x0008 - 0x0000)
struct MatchStats_setMatchStat final
{
public:
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x00827935_newValue;                       // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_setMatchStat) == 0x000004, "Wrong alignment on MatchStats_setMatchStat");
static_assert(sizeof(MatchStats_setMatchStat) == 0x000008, "Wrong size on MatchStats_setMatchStat");
static_assert(offsetof(MatchStats_setMatchStat, __verse_0x8C4546BB_statIndex) == 0x000000, "Member 'MatchStats_setMatchStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_setMatchStat, __verse_0x00827935_newValue) == 0x000004, "Member 'MatchStats_setMatchStat::__verse_0x00827935_newValue' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.setPlayerStat
// 0x0010 (0x0010 - 0x0000)
struct MatchStats_setPlayerStat final
{
public:
	class UPlayerComponent*                       __verse_0x9F1D658F_player;                         // 0x0000(0x0008)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x00827935_newValue;                       // 0x000C(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_setPlayerStat) == 0x000008, "Wrong alignment on MatchStats_setPlayerStat");
static_assert(sizeof(MatchStats_setPlayerStat) == 0x000010, "Wrong size on MatchStats_setPlayerStat");
static_assert(offsetof(MatchStats_setPlayerStat, __verse_0x9F1D658F_player) == 0x000000, "Member 'MatchStats_setPlayerStat::__verse_0x9F1D658F_player' has a wrong offset!");
static_assert(offsetof(MatchStats_setPlayerStat, __verse_0x8C4546BB_statIndex) == 0x000008, "Member 'MatchStats_setPlayerStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_setPlayerStat, __verse_0x00827935_newValue) == 0x00000C, "Member 'MatchStats_setPlayerStat::__verse_0x00827935_newValue' has a wrong offset!");

// Function VerseFortnite_MatchStats.MatchStats.setTeamStat
// 0x000C (0x000C - 0x0000)
struct MatchStats_setTeamStat final
{
public:
	int32                                         __verse_0x28201082_team;                           // 0x0000(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x8C4546BB_statIndex;                      // 0x0004(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	int32                                         __verse_0x00827935_newValue;                       // 0x0008(0x0004)(Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(MatchStats_setTeamStat) == 0x000004, "Wrong alignment on MatchStats_setTeamStat");
static_assert(sizeof(MatchStats_setTeamStat) == 0x00000C, "Wrong size on MatchStats_setTeamStat");
static_assert(offsetof(MatchStats_setTeamStat, __verse_0x28201082_team) == 0x000000, "Member 'MatchStats_setTeamStat::__verse_0x28201082_team' has a wrong offset!");
static_assert(offsetof(MatchStats_setTeamStat, __verse_0x8C4546BB_statIndex) == 0x000004, "Member 'MatchStats_setTeamStat::__verse_0x8C4546BB_statIndex' has a wrong offset!");
static_assert(offsetof(MatchStats_setTeamStat, __verse_0x00827935_newValue) == 0x000008, "Member 'MatchStats_setTeamStat::__verse_0x00827935_newValue' has a wrong offset!");

}

