#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WBP_UIKit_Block_Base

#include "Basic.hpp"

#include "WBP_UIKit_Block_Base_classes.hpp"
#include "WBP_UIKit_Block_Base_parameters.hpp"


namespace SDK
{

// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.SetDisabled
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_Block_Base_C::SetDisabled()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetDisabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.SetEnabled
// (Public, BlueprintCallable, BlueprintEvent)

void UWBP_UIKit_Block_Base_C::SetEnabled()
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("SetEnabled");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionDisabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionDisabled(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionDisabled");

	Params::WBP_UIKit_Block_Base_C_TransitionDisabled Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionEnabled
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionEnabled(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionEnabled");

	Params::WBP_UIKit_Block_Base_C_TransitionEnabled Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionFocused
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionFocused(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionFocused");

	Params::WBP_UIKit_Block_Base_C_TransitionFocused Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionHovered
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionHovered(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionHovered");

	Params::WBP_UIKit_Block_Base_C_TransitionHovered Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionPressed
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionPressed(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionPressed");

	Params::WBP_UIKit_Block_Base_C_TransitionPressed Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionReleased
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionReleased(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionReleased");

	Params::WBP_UIKit_Block_Base_C_TransitionReleased Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionState
// (Private, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 TransitionAnimation                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// double                                  TransitionTime                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// bool                                    PlayForward                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionState(class UWidgetAnimation* TransitionAnimation, double TransitionTime, bool PlayForward)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionState");

	Params::WBP_UIKit_Block_Base_C_TransitionState Parms{};

	Parms.TransitionAnimation = TransitionAnimation;
	Parms.TransitionTime = TransitionTime;
	Parms.PlayForward = PlayForward;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionUnfocused
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionUnfocused(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionUnfocused");

	Params::WBP_UIKit_Block_Base_C_TransitionUnfocused Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WBP_UIKit_Block_Base.WBP_UIKit_Block_Base_C.TransitionUnhovered
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidgetAnimation*                 AnimTransition                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UWBP_UIKit_Block_Base_C::TransitionUnhovered(class UWidgetAnimation* AnimTransition)
{
	static class UFunction* Func = nullptr;
	
	if (Func == nullptr)
		Func = Class->FindFunction("TransitionUnhovered");

	Params::WBP_UIKit_Block_Base_C_TransitionUnhovered Parms{};

	Parms.AnimTransition = AnimTransition;

	UObject::ProcessEvent(Func, &Parms);
}

}

