#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WeaponCraftingPanel

#include "Basic.hpp"

#include "WeaponCraftingPanel_classes.hpp"
#include "WeaponCraftingPanel_parameters.hpp"


namespace SDK
{

// Function WeaponCraftingPanel.WeaponCraftingPanel_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UWeaponCraftingPanel_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponCraftingPanel_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function WeaponCraftingPanel.WeaponCraftingPanel_C.ExecuteUbergraph_WeaponCraftingPanel
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWeaponCraftingPanel_C::ExecuteUbergraph_WeaponCraftingPanel(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponCraftingPanel_C", "ExecuteUbergraph_WeaponCraftingPanel");

	Params::WeaponCraftingPanel_C_ExecuteUbergraph_WeaponCraftingPanel Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function WeaponCraftingPanel.WeaponCraftingPanel_C.ListViewNavigation
// (Private, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EUINavigation                           Navigation_0                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class UWidget*                          ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, InstancedReference, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

class UWidget* UWeaponCraftingPanel_C::ListViewNavigation(EUINavigation Navigation_0)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponCraftingPanel_C", "ListViewNavigation");

	Params::WeaponCraftingPanel_C_ListViewNavigation Parms{};

	Parms.Navigation_0 = Navigation_0;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}


// Function WeaponCraftingPanel.WeaponCraftingPanel_C.OnFormulaListUpdated
// (Event, Protected, BlueprintEvent)
// Parameters:
// const int32                             NumFormulas                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UWeaponCraftingPanel_C::OnFormulaListUpdated(const int32 NumFormulas)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("WeaponCraftingPanel_C", "OnFormulaListUpdated");

	Params::WeaponCraftingPanel_C_OnFormulaListUpdated Parms{};

	Parms.NumFormulas = NumFormulas;

	UObject::ProcessEvent(Func, &Parms);
}

}

