#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: WestSausageFunctionLibrary

#include "Basic.hpp"

#include "Engine_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass WestSausageFunctionLibrary.WestSausageFunctionLibrary_C
// 0x0000 (0x0028 - 0x0028)
class UWestSausageFunctionLibrary_C final : public UBlueprintFunctionLibrary
{
public:
	static struct FVector CalculateDetachmentForce(class APlayerPawn_Athena_C* PlayerPawn, const struct FVector& VectorToAttachPoint, bool Launch, const struct FVector& LaunchVector, class UObject* __WorldContext);
	static bool ShouldDetach(class APlayerPawn_Athena_C* PlayerPawn, class UObject* __WorldContext);
	static void WestSausage_ShouldRotate(class UObject* __WorldContext, bool* ShouldRotate);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"WestSausageFunctionLibrary_C">();
	}
	static class UWestSausageFunctionLibrary_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UWestSausageFunctionLibrary_C>();
	}
};

}

