#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: XpReasonFeedItem

#include "Basic.hpp"

#include "CommonUI_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass XpReasonFeedItem.XpReasonFeedItem_C
// 0x0010 (0x0280 - 0x0270)
class UXpReasonFeedItem_C final : public UCommonUserWidget
{
public:
	class UWidgetAnimation*                       Present_PopIn;                                     // 0x0270(0x0008)(BlueprintVisible, BlueprintReadOnly, ZeroConstructor, Transient, IsPlainOldData, RepSkip, NoDestructor, HasGetValueTypeHash)
	class URichTextBlock*                         XpText;                                            // 0x0278(0x0008)(BlueprintVisible, ExportObject, ZeroConstructor, InstancedReference, IsPlainOldData, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	void SetXpText(const class FText& Text);
	void PlayPresentEffect(float PlaybackSpeed);

public:
	static class UClass* StaticClass()
	{
		return StaticBPGeneratedClassImpl<"XpReasonFeedItem_C">();
	}
	static class UXpReasonFeedItem_C* GetDefaultObj()
	{
		return GetDefaultObjImpl<UXpReasonFeedItem_C>();
	}
};

}

